from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class AbstractSignalBasedToISignalTriggeringMappingSubtypesEnum(Enum):
    ABSTRACT_SIGNAL_BASED_TO_I_SIGNAL_TRIGGERING_MAPPING = (
        "ABSTRACT-SIGNAL-BASED-TO-I-SIGNAL-TRIGGERING-MAPPING"
    )
    SIGNAL_BASED_EVENT_ELEMENT_TO_I_SIGNAL_TRIGGERING_MAPPING = (
        "SIGNAL-BASED-EVENT-ELEMENT-TO-I-SIGNAL-TRIGGERING-MAPPING"
    )
    SIGNAL_BASED_FIELD_TO_I_SIGNAL_TRIGGERING_MAPPING = (
        "SIGNAL-BASED-FIELD-TO-I-SIGNAL-TRIGGERING-MAPPING"
    )
    SIGNAL_BASED_METHOD_TO_I_SIGNAL_TRIGGERING_MAPPING = (
        "SIGNAL-BASED-METHOD-TO-I-SIGNAL-TRIGGERING-MAPPING"
    )
