from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class AdaptivePlatformServiceInstanceSubtypesEnum(Enum):
    ADAPTIVE_PLATFORM_SERVICE_INSTANCE = "ADAPTIVE-PLATFORM-SERVICE-INSTANCE"
    DDS_PROVIDED_SERVICE_INSTANCE = "DDS-PROVIDED-SERVICE-INSTANCE"
    DDS_REQUIRED_SERVICE_INSTANCE = "DDS-REQUIRED-SERVICE-INSTANCE"
    PROVIDED_AP_SERVICE_INSTANCE = "PROVIDED-AP-SERVICE-INSTANCE"
    PROVIDED_SOMEIP_SERVICE_INSTANCE = "PROVIDED-SOMEIP-SERVICE-INSTANCE"
    PROVIDED_USER_DEFINED_SERVICE_INSTANCE = (
        "PROVIDED-USER-DEFINED-SERVICE-INSTANCE"
    )
    REQUIRED_AP_SERVICE_INSTANCE = "REQUIRED-AP-SERVICE-INSTANCE"
    REQUIRED_SOMEIP_SERVICE_INSTANCE = "REQUIRED-SOMEIP-SERVICE-INSTANCE"
    REQUIRED_USER_DEFINED_SERVICE_INSTANCE = (
        "REQUIRED-USER-DEFINED-SERVICE-INSTANCE"
    )
