from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class ApplicationCompositeElementDataPrototypeSubtypesEnum(Enum):
    APPLICATION_ARRAY_ELEMENT = "APPLICATION-ARRAY-ELEMENT"
    APPLICATION_ASSOC_MAP_ELEMENT = "APPLICATION-ASSOC-MAP-ELEMENT"
    APPLICATION_COMPOSITE_ELEMENT_DATA_PROTOTYPE = (
        "APPLICATION-COMPOSITE-ELEMENT-DATA-PROTOTYPE"
    )
    APPLICATION_RECORD_ELEMENT = "APPLICATION-RECORD-ELEMENT"
