from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class ArElementSubtypesEnum(Enum):
    ABSTRACT_EXECUTION_CONTEXT = "ABSTRACT-EXECUTION-CONTEXT"
    ABSTRACT_IAM_REMOTE_SUBJECT = "ABSTRACT-IAM-REMOTE-SUBJECT"
    ABSTRACT_IMPLEMENTATION_DATA_TYPE = "ABSTRACT-IMPLEMENTATION-DATA-TYPE"
    ABSTRACT_RAW_DATA_STREAM_INTERFACE = "ABSTRACT-RAW-DATA-STREAM-INTERFACE"
    ABSTRACT_SYNCHRONIZED_TIME_BASE_INTERFACE = (
        "ABSTRACT-SYNCHRONIZED-TIME-BASE-INTERFACE"
    )
    ACL_OBJECT_SET = "ACL-OBJECT-SET"
    ACL_OPERATION = "ACL-OPERATION"
    ACL_PERMISSION = "ACL-PERMISSION"
    ACL_ROLE = "ACL-ROLE"
    ADAPTIVE_APPLICATION_SW_COMPONENT_TYPE = (
        "ADAPTIVE-APPLICATION-SW-COMPONENT-TYPE"
    )
    ADAPTIVE_PLATFORM_SERVICE_INSTANCE = "ADAPTIVE-PLATFORM-SERVICE-INSTANCE"
    ALIAS_NAME_SET = "ALIAS-NAME-SET"
    ALLOCATOR = "ALLOCATOR"
    AP_APPLICATION_ERROR = "AP-APPLICATION-ERROR"
    AP_APPLICATION_ERROR_DOMAIN = "AP-APPLICATION-ERROR-DOMAIN"
    AP_APPLICATION_ERROR_SET = "AP-APPLICATION-ERROR-SET"
    APPLICATION_ARRAY_DATA_TYPE = "APPLICATION-ARRAY-DATA-TYPE"
    APPLICATION_ASSOC_MAP_DATA_TYPE = "APPLICATION-ASSOC-MAP-DATA-TYPE"
    APPLICATION_COMPOSITE_DATA_TYPE = "APPLICATION-COMPOSITE-DATA-TYPE"
    APPLICATION_DATA_TYPE = "APPLICATION-DATA-TYPE"
    APPLICATION_DEFERRED_DATA_TYPE = "APPLICATION-DEFERRED-DATA-TYPE"
    APPLICATION_PARTITION = "APPLICATION-PARTITION"
    APPLICATION_PRIMITIVE_DATA_TYPE = "APPLICATION-PRIMITIVE-DATA-TYPE"
    APPLICATION_RECORD_DATA_TYPE = "APPLICATION-RECORD-DATA-TYPE"
    APPLICATION_SW_COMPONENT_TYPE = "APPLICATION-SW-COMPONENT-TYPE"
    AR_ELEMENT = "AR-ELEMENT"
    ATOMIC_SW_COMPONENT_TYPE = "ATOMIC-SW-COMPONENT-TYPE"
    AUTOSAR_DATA_TYPE = "AUTOSAR-DATA-TYPE"
    BASE_TYPE = "BASE-TYPE"
    BLUEPRINT_MAPPING_SET = "BLUEPRINT-MAPPING-SET"
    BSW_COMPOSITION_TIMING = "BSW-COMPOSITION-TIMING"
    BSW_ENTRY_RELATIONSHIP_SET = "BSW-ENTRY-RELATIONSHIP-SET"
    BSW_IMPLEMENTATION = "BSW-IMPLEMENTATION"
    BSW_MODULE_DESCRIPTION = "BSW-MODULE-DESCRIPTION"
    BSW_MODULE_ENTRY = "BSW-MODULE-ENTRY"
    BSW_MODULE_TIMING = "BSW-MODULE-TIMING"
    BUILD_ACTION_MANIFEST = "BUILD-ACTION-MANIFEST"
    CALIBRATION_PARAMETER_VALUE_SET = "CALIBRATION-PARAMETER-VALUE-SET"
    CLIENT_ID_DEFINITION_SET = "CLIENT-ID-DEFINITION-SET"
    CLIENT_SERVER_INTERFACE = "CLIENT-SERVER-INTERFACE"
    CLIENT_SERVER_INTERFACE_TO_BSW_MODULE_ENTRY_BLUEPRINT_MAPPING = (
        "CLIENT-SERVER-INTERFACE-TO-BSW-MODULE-ENTRY-BLUEPRINT-MAPPING"
    )
    COLLECTION = "COLLECTION"
    COM_CERTIFICATE_TO_CRYPTO_CERTIFICATE_MAPPING = (
        "COM-CERTIFICATE-TO-CRYPTO-CERTIFICATE-MAPPING"
    )
    COM_EVENT_GRANT = "COM-EVENT-GRANT"
    COM_EVENT_GRANT_DESIGN = "COM-EVENT-GRANT-DESIGN"
    COM_FIELD_GRANT = "COM-FIELD-GRANT"
    COM_FIELD_GRANT_DESIGN = "COM-FIELD-GRANT-DESIGN"
    COM_FIND_SERVICE_GRANT = "COM-FIND-SERVICE-GRANT"
    COM_FIND_SERVICE_GRANT_DESIGN = "COM-FIND-SERVICE-GRANT-DESIGN"
    COM_GRANT = "COM-GRANT"
    COM_GRANT_DESIGN = "COM-GRANT-DESIGN"
    COM_KEY_TO_CRYPTO_KEY_SLOT_MAPPING = "COM-KEY-TO-CRYPTO-KEY-SLOT-MAPPING"
    COM_METHOD_GRANT = "COM-METHOD-GRANT"
    COM_METHOD_GRANT_DESIGN = "COM-METHOD-GRANT-DESIGN"
    COM_OFFER_SERVICE_GRANT = "COM-OFFER-SERVICE-GRANT"
    COM_OFFER_SERVICE_GRANT_DESIGN = "COM-OFFER-SERVICE-GRANT-DESIGN"
    COM_SEC_OC_TO_CRYPTO_KEY_SLOT_MAPPING = (
        "COM-SEC-OC-TO-CRYPTO-KEY-SLOT-MAPPING"
    )
    COMPLEX_DEVICE_DRIVER_SW_COMPONENT_TYPE = (
        "COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE"
    )
    COMPOSITE_INTERFACE = "COMPOSITE-INTERFACE"
    COMPOSITION_P_PORT_TO_EXECUTABLE_P_PORT_MAPPING = (
        "COMPOSITION-P-PORT-TO-EXECUTABLE-P-PORT-MAPPING"
    )
    COMPOSITION_PORT_TO_EXECUTABLE_PORT_MAPPING = (
        "COMPOSITION-PORT-TO-EXECUTABLE-PORT-MAPPING"
    )
    COMPOSITION_R_PORT_TO_EXECUTABLE_R_PORT_MAPPING = (
        "COMPOSITION-R-PORT-TO-EXECUTABLE-R-PORT-MAPPING"
    )
    COMPOSITION_SW_COMPONENT_TYPE = "COMPOSITION-SW-COMPONENT-TYPE"
    COMPU_METHOD = "COMPU-METHOD"
    CONSISTENCY_NEEDS_BLUEPRINT_SET = "CONSISTENCY-NEEDS-BLUEPRINT-SET"
    CONSTANT_SPECIFICATION = "CONSTANT-SPECIFICATION"
    CONSTANT_SPECIFICATION_MAPPING_SET = "CONSTANT-SPECIFICATION-MAPPING-SET"
    CP_SOFTWARE_CLUSTER = "CP-SOFTWARE-CLUSTER"
    CP_SOFTWARE_CLUSTER_BINARY_MANIFEST_DESCRIPTOR = (
        "CP-SOFTWARE-CLUSTER-BINARY-MANIFEST-DESCRIPTOR"
    )
    CP_SOFTWARE_CLUSTER_MAPPING_SET = "CP-SOFTWARE-CLUSTER-MAPPING-SET"
    CP_SOFTWARE_CLUSTER_RESOURCE_POOL = "CP-SOFTWARE-CLUSTER-RESOURCE-POOL"
    CPP_IMPLEMENTATION_DATA_TYPE = "CPP-IMPLEMENTATION-DATA-TYPE"
    CRYPTO_CERTIFICATE_INTERFACE = "CRYPTO-CERTIFICATE-INTERFACE"
    CRYPTO_CERTIFICATE_TO_PORT_PROTOTYPE_MAPPING = (
        "CRYPTO-CERTIFICATE-TO-PORT-PROTOTYPE-MAPPING"
    )
    CRYPTO_INTERFACE = "CRYPTO-INTERFACE"
    CRYPTO_KEY_SLOT_INTERFACE = "CRYPTO-KEY-SLOT-INTERFACE"
    CRYPTO_KEY_SLOT_TO_PORT_PROTOTYPE_MAPPING = (
        "CRYPTO-KEY-SLOT-TO-PORT-PROTOTYPE-MAPPING"
    )
    CRYPTO_NEED_TO_PORT_PROTOTYPE_MAPPING = (
        "CRYPTO-NEED-TO-PORT-PROTOTYPE-MAPPING"
    )
    CRYPTO_PROVIDER_INTERFACE = "CRYPTO-PROVIDER-INTERFACE"
    CRYPTO_PROVIDER_TO_PORT_PROTOTYPE_MAPPING = (
        "CRYPTO-PROVIDER-TO-PORT-PROTOTYPE-MAPPING"
    )
    CRYPTO_SERVICE_CERTIFICATE = "CRYPTO-SERVICE-CERTIFICATE"
    CRYPTO_SERVICE_KEY = "CRYPTO-SERVICE-KEY"
    CRYPTO_SERVICE_PRIMITIVE = "CRYPTO-SERVICE-PRIMITIVE"
    CRYPTO_SERVICE_QUEUE = "CRYPTO-SERVICE-QUEUE"
    CRYPTO_TRUST_MASTER_INTERFACE = "CRYPTO-TRUST-MASTER-INTERFACE"
    CUSTOM_CPP_IMPLEMENTATION_DATA_TYPE = "CUSTOM-CPP-IMPLEMENTATION-DATA-TYPE"
    DATA_CONSTR = "DATA-CONSTR"
    DATA_EXCHANGE_POINT = "DATA-EXCHANGE-POINT"
    DATA_INTERFACE = "DATA-INTERFACE"
    DATA_TRANSFORMATION_SET = "DATA-TRANSFORMATION-SET"
    DATA_TYPE_MAPPING_SET = "DATA-TYPE-MAPPING-SET"
    DDS_PROVIDED_SERVICE_INSTANCE = "DDS-PROVIDED-SERVICE-INSTANCE"
    DDS_REQUIRED_SERVICE_INSTANCE = "DDS-REQUIRED-SERVICE-INSTANCE"
    DDS_SERVICE_INSTANCE_TO_MACHINE_MAPPING = (
        "DDS-SERVICE-INSTANCE-TO-MACHINE-MAPPING"
    )
    DDS_SERVICE_INTERFACE_DEPLOYMENT = "DDS-SERVICE-INTERFACE-DEPLOYMENT"
    DETERMINISTIC_CLIENT = "DETERMINISTIC-CLIENT"
    DIAGNOSTIC_ABSTRACT_ALIAS_EVENT = "DIAGNOSTIC-ABSTRACT-ALIAS-EVENT"
    DIAGNOSTIC_ABSTRACT_DATA_IDENTIFIER = "DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER"
    DIAGNOSTIC_ABSTRACT_DATA_IDENTIFIER_INTERFACE = (
        "DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER-INTERFACE"
    )
    DIAGNOSTIC_ABSTRACT_ROUTINE_INTERFACE = (
        "DIAGNOSTIC-ABSTRACT-ROUTINE-INTERFACE"
    )
    DIAGNOSTIC_ACCESS_PERMISSION = "DIAGNOSTIC-ACCESS-PERMISSION"
    DIAGNOSTIC_AGING = "DIAGNOSTIC-AGING"
    DIAGNOSTIC_CLEAR_CONDITION = "DIAGNOSTIC-CLEAR-CONDITION"
    DIAGNOSTIC_CLEAR_CONDITION_GROUP = "DIAGNOSTIC-CLEAR-CONDITION-GROUP"
    DIAGNOSTIC_CLEAR_CONDITION_PORT_MAPPING = (
        "DIAGNOSTIC-CLEAR-CONDITION-PORT-MAPPING"
    )
    DIAGNOSTIC_CLEAR_DIAGNOSTIC_INFORMATION = (
        "DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION"
    )
    DIAGNOSTIC_CLEAR_DIAGNOSTIC_INFORMATION_CLASS = (
        "DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS"
    )
    DIAGNOSTIC_CLEAR_RESET_EMISSION_RELATED_INFO = (
        "DIAGNOSTIC-CLEAR-RESET-EMISSION-RELATED-INFO"
    )
    DIAGNOSTIC_CLEAR_RESET_EMISSION_RELATED_INFO_CLASS = (
        "DIAGNOSTIC-CLEAR-RESET-EMISSION-RELATED-INFO-CLASS"
    )
    DIAGNOSTIC_COM_CONTROL = "DIAGNOSTIC-COM-CONTROL"
    DIAGNOSTIC_COM_CONTROL_CLASS = "DIAGNOSTIC-COM-CONTROL-CLASS"
    DIAGNOSTIC_COMMON_ELEMENT = "DIAGNOSTIC-COMMON-ELEMENT"
    DIAGNOSTIC_CONDITION = "DIAGNOSTIC-CONDITION"
    DIAGNOSTIC_CONDITION_GROUP = "DIAGNOSTIC-CONDITION-GROUP"
    DIAGNOSTIC_CONDITION_INTERFACE = "DIAGNOSTIC-CONDITION-INTERFACE"
    DIAGNOSTIC_CONNECTION = "DIAGNOSTIC-CONNECTION"
    DIAGNOSTIC_CONTRIBUTION_SET = "DIAGNOSTIC-CONTRIBUTION-SET"
    DIAGNOSTIC_CONTROL_DTC_SETTING = "DIAGNOSTIC-CONTROL-DTC-SETTING"
    DIAGNOSTIC_CONTROL_DTC_SETTING_CLASS = (
        "DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS"
    )
    DIAGNOSTIC_CUSTOM_SERVICE_CLASS = "DIAGNOSTIC-CUSTOM-SERVICE-CLASS"
    DIAGNOSTIC_CUSTOM_SERVICE_INSTANCE = "DIAGNOSTIC-CUSTOM-SERVICE-INSTANCE"
    DIAGNOSTIC_DATA_BY_IDENTIFIER = "DIAGNOSTIC-DATA-BY-IDENTIFIER"
    DIAGNOSTIC_DATA_ELEMENT_INTERFACE = "DIAGNOSTIC-DATA-ELEMENT-INTERFACE"
    DIAGNOSTIC_DATA_IDENTIFIER = "DIAGNOSTIC-DATA-IDENTIFIER"
    DIAGNOSTIC_DATA_IDENTIFIER_GENERIC_INTERFACE = (
        "DIAGNOSTIC-DATA-IDENTIFIER-GENERIC-INTERFACE"
    )
    DIAGNOSTIC_DATA_IDENTIFIER_INTERFACE = (
        "DIAGNOSTIC-DATA-IDENTIFIER-INTERFACE"
    )
    DIAGNOSTIC_DATA_IDENTIFIER_SET = "DIAGNOSTIC-DATA-IDENTIFIER-SET"
    DIAGNOSTIC_DATA_TRANSFER = "DIAGNOSTIC-DATA-TRANSFER"
    DIAGNOSTIC_DATA_TRANSFER_CLASS = "DIAGNOSTIC-DATA-TRANSFER-CLASS"
    DIAGNOSTIC_DEM_PROVIDED_DATA_MAPPING = (
        "DIAGNOSTIC-DEM-PROVIDED-DATA-MAPPING"
    )
    DIAGNOSTIC_DO_IP_ACTIVATION_LINE_INTERFACE = (
        "DIAGNOSTIC-DO-IP-ACTIVATION-LINE-INTERFACE"
    )
    DIAGNOSTIC_DO_IP_GROUP_IDENTIFICATION_INTERFACE = (
        "DIAGNOSTIC-DO-IP-GROUP-IDENTIFICATION-INTERFACE"
    )
    DIAGNOSTIC_DO_IP_POWER_MODE_INTERFACE = (
        "DIAGNOSTIC-DO-IP-POWER-MODE-INTERFACE"
    )
    DIAGNOSTIC_DO_IP_TRIGGER_VEHICLE_ANNOUNCEMENT_INTERFACE = (
        "DIAGNOSTIC-DO-IP-TRIGGER-VEHICLE-ANNOUNCEMENT-INTERFACE"
    )
    DIAGNOSTIC_DOWNLOAD_INTERFACE = "DIAGNOSTIC-DOWNLOAD-INTERFACE"
    DIAGNOSTIC_DTC_INFORMATION_INTERFACE = (
        "DIAGNOSTIC-DTC-INFORMATION-INTERFACE"
    )
    DIAGNOSTIC_DYNAMIC_DATA_IDENTIFIER = "DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER"
    DIAGNOSTIC_DYNAMICALLY_DEFINE_DATA_IDENTIFIER = (
        "DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER"
    )
    DIAGNOSTIC_DYNAMICALLY_DEFINE_DATA_IDENTIFIER_CLASS = (
        "DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS"
    )
    DIAGNOSTIC_ECU_INSTANCE_PROPS = "DIAGNOSTIC-ECU-INSTANCE-PROPS"
    DIAGNOSTIC_ECU_RESET = "DIAGNOSTIC-ECU-RESET"
    DIAGNOSTIC_ECU_RESET_CLASS = "DIAGNOSTIC-ECU-RESET-CLASS"
    DIAGNOSTIC_ECU_RESET_INTERFACE = "DIAGNOSTIC-ECU-RESET-INTERFACE"
    DIAGNOSTIC_ENABLE_CONDITION = "DIAGNOSTIC-ENABLE-CONDITION"
    DIAGNOSTIC_ENABLE_CONDITION_GROUP = "DIAGNOSTIC-ENABLE-CONDITION-GROUP"
    DIAGNOSTIC_ENABLE_CONDITION_PORT_MAPPING = (
        "DIAGNOSTIC-ENABLE-CONDITION-PORT-MAPPING"
    )
    DIAGNOSTIC_ENVIRONMENTAL_CONDITION = "DIAGNOSTIC-ENVIRONMENTAL-CONDITION"
    DIAGNOSTIC_EVENT = "DIAGNOSTIC-EVENT"
    DIAGNOSTIC_EVENT_INTERFACE = "DIAGNOSTIC-EVENT-INTERFACE"
    DIAGNOSTIC_EVENT_PORT_MAPPING = "DIAGNOSTIC-EVENT-PORT-MAPPING"
    DIAGNOSTIC_EVENT_TO_DEBOUNCE_ALGORITHM_MAPPING = (
        "DIAGNOSTIC-EVENT-TO-DEBOUNCE-ALGORITHM-MAPPING"
    )
    DIAGNOSTIC_EVENT_TO_ENABLE_CONDITION_GROUP_MAPPING = (
        "DIAGNOSTIC-EVENT-TO-ENABLE-CONDITION-GROUP-MAPPING"
    )
    DIAGNOSTIC_EVENT_TO_OPERATION_CYCLE_MAPPING = (
        "DIAGNOSTIC-EVENT-TO-OPERATION-CYCLE-MAPPING"
    )
    DIAGNOSTIC_EVENT_TO_SECURITY_EVENT_MAPPING = (
        "DIAGNOSTIC-EVENT-TO-SECURITY-EVENT-MAPPING"
    )
    DIAGNOSTIC_EVENT_TO_STORAGE_CONDITION_GROUP_MAPPING = (
        "DIAGNOSTIC-EVENT-TO-STORAGE-CONDITION-GROUP-MAPPING"
    )
    DIAGNOSTIC_EVENT_TO_TROUBLE_CODE_J_1939_MAPPING = (
        "DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-J-1939-MAPPING"
    )
    DIAGNOSTIC_EVENT_TO_TROUBLE_CODE_UDS_MAPPING = (
        "DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-UDS-MAPPING"
    )
    DIAGNOSTIC_EXTENDED_DATA_RECORD = "DIAGNOSTIC-EXTENDED-DATA-RECORD"
    DIAGNOSTIC_FIM_ALIAS_EVENT = "DIAGNOSTIC-FIM-ALIAS-EVENT"
    DIAGNOSTIC_FIM_ALIAS_EVENT_GROUP = "DIAGNOSTIC-FIM-ALIAS-EVENT-GROUP"
    DIAGNOSTIC_FIM_ALIAS_EVENT_GROUP_MAPPING = (
        "DIAGNOSTIC-FIM-ALIAS-EVENT-GROUP-MAPPING"
    )
    DIAGNOSTIC_FIM_ALIAS_EVENT_MAPPING = "DIAGNOSTIC-FIM-ALIAS-EVENT-MAPPING"
    DIAGNOSTIC_FIM_EVENT_GROUP = "DIAGNOSTIC-FIM-EVENT-GROUP"
    DIAGNOSTIC_FIM_FUNCTION_MAPPING = "DIAGNOSTIC-FIM-FUNCTION-MAPPING"
    DIAGNOSTIC_FREEZE_FRAME = "DIAGNOSTIC-FREEZE-FRAME"
    DIAGNOSTIC_FUNCTION_IDENTIFIER = "DIAGNOSTIC-FUNCTION-IDENTIFIER"
    DIAGNOSTIC_FUNCTION_IDENTIFIER_INHIBIT = (
        "DIAGNOSTIC-FUNCTION-IDENTIFIER-INHIBIT"
    )
    DIAGNOSTIC_GENERIC_UDS_INTERFACE = "DIAGNOSTIC-GENERIC-UDS-INTERFACE"
    DIAGNOSTIC_INDICATOR = "DIAGNOSTIC-INDICATOR"
    DIAGNOSTIC_INDICATOR_INTERFACE = "DIAGNOSTIC-INDICATOR-INTERFACE"
    DIAGNOSTIC_INDICATOR_PORT_MAPPING = "DIAGNOSTIC-INDICATOR-PORT-MAPPING"
    DIAGNOSTIC_INFO_TYPE = "DIAGNOSTIC-INFO-TYPE"
    DIAGNOSTIC_INHIBIT_SOURCE_EVENT_MAPPING = (
        "DIAGNOSTIC-INHIBIT-SOURCE-EVENT-MAPPING"
    )
    DIAGNOSTIC_IO_CONTROL = "DIAGNOSTIC-IO-CONTROL"
    DIAGNOSTIC_IO_CONTROL_CLASS = "DIAGNOSTIC-IO-CONTROL-CLASS"
    DIAGNOSTIC_IUMPR = "DIAGNOSTIC-IUMPR"
    DIAGNOSTIC_IUMPR_DENOMINATOR_GROUP = "DIAGNOSTIC-IUMPR-DENOMINATOR-GROUP"
    DIAGNOSTIC_IUMPR_GROUP = "DIAGNOSTIC-IUMPR-GROUP"
    DIAGNOSTIC_J_1939_EXPANDED_FREEZE_FRAME = (
        "DIAGNOSTIC-J-1939-EXPANDED-FREEZE-FRAME"
    )
    DIAGNOSTIC_J_1939_FREEZE_FRAME = "DIAGNOSTIC-J-1939-FREEZE-FRAME"
    DIAGNOSTIC_J_1939_NODE = "DIAGNOSTIC-J-1939-NODE"
    DIAGNOSTIC_J_1939_SPN = "DIAGNOSTIC-J-1939-SPN"
    DIAGNOSTIC_J_1939_SPN_MAPPING = "DIAGNOSTIC-J-1939-SPN-MAPPING"
    DIAGNOSTIC_J_1939_SW_MAPPING = "DIAGNOSTIC-J-1939-SW-MAPPING"
    DIAGNOSTIC_MAPPING = "DIAGNOSTIC-MAPPING"
    DIAGNOSTIC_MASTER_TO_SLAVE_EVENT_MAPPING = (
        "DIAGNOSTIC-MASTER-TO-SLAVE-EVENT-MAPPING"
    )
    DIAGNOSTIC_MASTER_TO_SLAVE_EVENT_MAPPING_SET = (
        "DIAGNOSTIC-MASTER-TO-SLAVE-EVENT-MAPPING-SET"
    )
    DIAGNOSTIC_MEASUREMENT_IDENTIFIER = "DIAGNOSTIC-MEASUREMENT-IDENTIFIER"
    DIAGNOSTIC_MEMORY_ADDRESSABLE_RANGE_ACCESS = (
        "DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS"
    )
    DIAGNOSTIC_MEMORY_BY_ADDRESS = "DIAGNOSTIC-MEMORY-BY-ADDRESS"
    DIAGNOSTIC_MEMORY_DESTINATION = "DIAGNOSTIC-MEMORY-DESTINATION"
    DIAGNOSTIC_MEMORY_DESTINATION_MIRROR = (
        "DIAGNOSTIC-MEMORY-DESTINATION-MIRROR"
    )
    DIAGNOSTIC_MEMORY_DESTINATION_PORT_MAPPING = (
        "DIAGNOSTIC-MEMORY-DESTINATION-PORT-MAPPING"
    )
    DIAGNOSTIC_MEMORY_DESTINATION_PRIMARY = (
        "DIAGNOSTIC-MEMORY-DESTINATION-PRIMARY"
    )
    DIAGNOSTIC_MEMORY_DESTINATION_USER_DEFINED = (
        "DIAGNOSTIC-MEMORY-DESTINATION-USER-DEFINED"
    )
    DIAGNOSTIC_MEMORY_IDENTIFIER = "DIAGNOSTIC-MEMORY-IDENTIFIER"
    DIAGNOSTIC_MONITOR_INTERFACE = "DIAGNOSTIC-MONITOR-INTERFACE"
    DIAGNOSTIC_OPERATION_CYCLE = "DIAGNOSTIC-OPERATION-CYCLE"
    DIAGNOSTIC_OPERATION_CYCLE_INTERFACE = (
        "DIAGNOSTIC-OPERATION-CYCLE-INTERFACE"
    )
    DIAGNOSTIC_OPERATION_CYCLE_PORT_MAPPING = (
        "DIAGNOSTIC-OPERATION-CYCLE-PORT-MAPPING"
    )
    DIAGNOSTIC_PARAMETER_IDENTIFIER = "DIAGNOSTIC-PARAMETER-IDENTIFIER"
    DIAGNOSTIC_PORT_INTERFACE = "DIAGNOSTIC-PORT-INTERFACE"
    DIAGNOSTIC_POWERTRAIN_FREEZE_FRAME = "DIAGNOSTIC-POWERTRAIN-FREEZE-FRAME"
    DIAGNOSTIC_PROTOCOL = "DIAGNOSTIC-PROTOCOL"
    DIAGNOSTIC_PROVIDED_DATA_MAPPING = "DIAGNOSTIC-PROVIDED-DATA-MAPPING"
    DIAGNOSTIC_READ_DATA_BY_IDENTIFIER = "DIAGNOSTIC-READ-DATA-BY-IDENTIFIER"
    DIAGNOSTIC_READ_DATA_BY_IDENTIFIER_CLASS = (
        "DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS"
    )
    DIAGNOSTIC_READ_DATA_BY_PERIODIC_ID = "DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID"
    DIAGNOSTIC_READ_DATA_BY_PERIODIC_ID_CLASS = (
        "DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS"
    )
    DIAGNOSTIC_READ_DTC_INFORMATION = "DIAGNOSTIC-READ-DTC-INFORMATION"
    DIAGNOSTIC_READ_DTC_INFORMATION_CLASS = (
        "DIAGNOSTIC-READ-DTC-INFORMATION-CLASS"
    )
    DIAGNOSTIC_READ_MEMORY_BY_ADDRESS = "DIAGNOSTIC-READ-MEMORY-BY-ADDRESS"
    DIAGNOSTIC_READ_MEMORY_BY_ADDRESS_CLASS = (
        "DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS"
    )
    DIAGNOSTIC_READ_SCALING_DATA_BY_IDENTIFIER = (
        "DIAGNOSTIC-READ-SCALING-DATA-BY-IDENTIFIER"
    )
    DIAGNOSTIC_READ_SCALING_DATA_BY_IDENTIFIER_CLASS = (
        "DIAGNOSTIC-READ-SCALING-DATA-BY-IDENTIFIER-CLASS"
    )
    DIAGNOSTIC_REQUEST_CONTROL_OF_ON_BOARD_DEVICE = (
        "DIAGNOSTIC-REQUEST-CONTROL-OF-ON-BOARD-DEVICE"
    )
    DIAGNOSTIC_REQUEST_CONTROL_OF_ON_BOARD_DEVICE_CLASS = (
        "DIAGNOSTIC-REQUEST-CONTROL-OF-ON-BOARD-DEVICE-CLASS"
    )
    DIAGNOSTIC_REQUEST_CURRENT_POWERTRAIN_DATA = (
        "DIAGNOSTIC-REQUEST-CURRENT-POWERTRAIN-DATA"
    )
    DIAGNOSTIC_REQUEST_CURRENT_POWERTRAIN_DATA_CLASS = (
        "DIAGNOSTIC-REQUEST-CURRENT-POWERTRAIN-DATA-CLASS"
    )
    DIAGNOSTIC_REQUEST_DOWNLOAD = "DIAGNOSTIC-REQUEST-DOWNLOAD"
    DIAGNOSTIC_REQUEST_DOWNLOAD_CLASS = "DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS"
    DIAGNOSTIC_REQUEST_EMISSION_RELATED_DTC = (
        "DIAGNOSTIC-REQUEST-EMISSION-RELATED-DTC"
    )
    DIAGNOSTIC_REQUEST_EMISSION_RELATED_DTC_CLASS = (
        "DIAGNOSTIC-REQUEST-EMISSION-RELATED-DTC-CLASS"
    )
    DIAGNOSTIC_REQUEST_EMISSION_RELATED_DTC_PERMANENT_STATUS = (
        "DIAGNOSTIC-REQUEST-EMISSION-RELATED-DTC-PERMANENT-STATUS"
    )
    DIAGNOSTIC_REQUEST_EMISSION_RELATED_DTC_PERMANENT_STATUS_CLASS = (
        "DIAGNOSTIC-REQUEST-EMISSION-RELATED-DTC-PERMANENT-STATUS-CLASS"
    )
    DIAGNOSTIC_REQUEST_FILE_TRANSFER = "DIAGNOSTIC-REQUEST-FILE-TRANSFER"
    DIAGNOSTIC_REQUEST_FILE_TRANSFER_CLASS = (
        "DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS"
    )
    DIAGNOSTIC_REQUEST_ON_BOARD_MONITORING_TEST_RESULTS = (
        "DIAGNOSTIC-REQUEST-ON-BOARD-MONITORING-TEST-RESULTS"
    )
    DIAGNOSTIC_REQUEST_ON_BOARD_MONITORING_TEST_RESULTS_CLASS = (
        "DIAGNOSTIC-REQUEST-ON-BOARD-MONITORING-TEST-RESULTS-CLASS"
    )
    DIAGNOSTIC_REQUEST_POWERTRAIN_FREEZE_FRAME_DATA = (
        "DIAGNOSTIC-REQUEST-POWERTRAIN-FREEZE-FRAME-DATA"
    )
    DIAGNOSTIC_REQUEST_POWERTRAIN_FREEZE_FRAME_DATA_CLASS = (
        "DIAGNOSTIC-REQUEST-POWERTRAIN-FREEZE-FRAME-DATA-CLASS"
    )
    DIAGNOSTIC_REQUEST_UPLOAD = "DIAGNOSTIC-REQUEST-UPLOAD"
    DIAGNOSTIC_REQUEST_UPLOAD_CLASS = "DIAGNOSTIC-REQUEST-UPLOAD-CLASS"
    DIAGNOSTIC_REQUEST_VEHICLE_INFO = "DIAGNOSTIC-REQUEST-VEHICLE-INFO"
    DIAGNOSTIC_REQUEST_VEHICLE_INFO_CLASS = (
        "DIAGNOSTIC-REQUEST-VEHICLE-INFO-CLASS"
    )
    DIAGNOSTIC_RESPONSE_ON_EVENT = "DIAGNOSTIC-RESPONSE-ON-EVENT"
    DIAGNOSTIC_RESPONSE_ON_EVENT_CLASS = "DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS"
    DIAGNOSTIC_ROUTINE = "DIAGNOSTIC-ROUTINE"
    DIAGNOSTIC_ROUTINE_CONTROL = "DIAGNOSTIC-ROUTINE-CONTROL"
    DIAGNOSTIC_ROUTINE_CONTROL_CLASS = "DIAGNOSTIC-ROUTINE-CONTROL-CLASS"
    DIAGNOSTIC_ROUTINE_GENERIC_INTERFACE = (
        "DIAGNOSTIC-ROUTINE-GENERIC-INTERFACE"
    )
    DIAGNOSTIC_ROUTINE_INTERFACE = "DIAGNOSTIC-ROUTINE-INTERFACE"
    DIAGNOSTIC_SECURITY_ACCESS = "DIAGNOSTIC-SECURITY-ACCESS"
    DIAGNOSTIC_SECURITY_ACCESS_CLASS = "DIAGNOSTIC-SECURITY-ACCESS-CLASS"
    DIAGNOSTIC_SECURITY_EVENT_REPORTING_MODE_MAPPING = (
        "DIAGNOSTIC-SECURITY-EVENT-REPORTING-MODE-MAPPING"
    )
    DIAGNOSTIC_SECURITY_LEVEL = "DIAGNOSTIC-SECURITY-LEVEL"
    DIAGNOSTIC_SECURITY_LEVEL_INTERFACE = "DIAGNOSTIC-SECURITY-LEVEL-INTERFACE"
    DIAGNOSTIC_SECURITY_LEVEL_PORT_MAPPING = (
        "DIAGNOSTIC-SECURITY-LEVEL-PORT-MAPPING"
    )
    DIAGNOSTIC_SERVICE_CLASS = "DIAGNOSTIC-SERVICE-CLASS"
    DIAGNOSTIC_SERVICE_DATA_IDENTIFIER_PORT_MAPPING = (
        "DIAGNOSTIC-SERVICE-DATA-IDENTIFIER-PORT-MAPPING"
    )
    DIAGNOSTIC_SERVICE_DATA_MAPPING = "DIAGNOSTIC-SERVICE-DATA-MAPPING"
    DIAGNOSTIC_SERVICE_GENERIC_MAPPING = "DIAGNOSTIC-SERVICE-GENERIC-MAPPING"
    DIAGNOSTIC_SERVICE_INSTANCE = "DIAGNOSTIC-SERVICE-INSTANCE"
    DIAGNOSTIC_SERVICE_SW_MAPPING = "DIAGNOSTIC-SERVICE-SW-MAPPING"
    DIAGNOSTIC_SERVICE_TABLE = "DIAGNOSTIC-SERVICE-TABLE"
    DIAGNOSTIC_SERVICE_VALIDATION_INTERFACE = (
        "DIAGNOSTIC-SERVICE-VALIDATION-INTERFACE"
    )
    DIAGNOSTIC_SESSION = "DIAGNOSTIC-SESSION"
    DIAGNOSTIC_SESSION_CONTROL = "DIAGNOSTIC-SESSION-CONTROL"
    DIAGNOSTIC_SESSION_CONTROL_CLASS = "DIAGNOSTIC-SESSION-CONTROL-CLASS"
    DIAGNOSTIC_SOFTWARE_CLUSTER_PROPS = "DIAGNOSTIC-SOFTWARE-CLUSTER-PROPS"
    DIAGNOSTIC_STORAGE_CONDITION = "DIAGNOSTIC-STORAGE-CONDITION"
    DIAGNOSTIC_STORAGE_CONDITION_GROUP = "DIAGNOSTIC-STORAGE-CONDITION-GROUP"
    DIAGNOSTIC_STORAGE_CONDITION_PORT_MAPPING = (
        "DIAGNOSTIC-STORAGE-CONDITION-PORT-MAPPING"
    )
    DIAGNOSTIC_SW_MAPPING = "DIAGNOSTIC-SW-MAPPING"
    DIAGNOSTIC_TEST_RESULT = "DIAGNOSTIC-TEST-RESULT"
    DIAGNOSTIC_TEST_ROUTINE_IDENTIFIER = "DIAGNOSTIC-TEST-ROUTINE-IDENTIFIER"
    DIAGNOSTIC_TRANSFER_EXIT = "DIAGNOSTIC-TRANSFER-EXIT"
    DIAGNOSTIC_TRANSFER_EXIT_CLASS = "DIAGNOSTIC-TRANSFER-EXIT-CLASS"
    DIAGNOSTIC_TROUBLE_CODE = "DIAGNOSTIC-TROUBLE-CODE"
    DIAGNOSTIC_TROUBLE_CODE_GROUP = "DIAGNOSTIC-TROUBLE-CODE-GROUP"
    DIAGNOSTIC_TROUBLE_CODE_J_1939 = "DIAGNOSTIC-TROUBLE-CODE-J-1939"
    DIAGNOSTIC_TROUBLE_CODE_OBD = "DIAGNOSTIC-TROUBLE-CODE-OBD"
    DIAGNOSTIC_TROUBLE_CODE_PROPS = "DIAGNOSTIC-TROUBLE-CODE-PROPS"
    DIAGNOSTIC_TROUBLE_CODE_UDS = "DIAGNOSTIC-TROUBLE-CODE-UDS"
    DIAGNOSTIC_TROUBLE_CODE_UDS_TO_CLEAR_CONDITION_GROUP_MAPPING = (
        "DIAGNOSTIC-TROUBLE-CODE-UDS-TO-CLEAR-CONDITION-GROUP-MAPPING"
    )
    DIAGNOSTIC_TROUBLE_CODE_UDS_TO_TROUBLE_CODE_OBD_MAPPING = (
        "DIAGNOSTIC-TROUBLE-CODE-UDS-TO-TROUBLE-CODE-OBD-MAPPING"
    )
    DIAGNOSTIC_UPLOAD_INTERFACE = "DIAGNOSTIC-UPLOAD-INTERFACE"
    DIAGNOSTIC_WRITE_DATA_BY_IDENTIFIER = "DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER"
    DIAGNOSTIC_WRITE_DATA_BY_IDENTIFIER_CLASS = (
        "DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS"
    )
    DIAGNOSTIC_WRITE_MEMORY_BY_ADDRESS = "DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS"
    DIAGNOSTIC_WRITE_MEMORY_BY_ADDRESS_CLASS = (
        "DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS"
    )
    DLT_LOG_CHANNEL_DESIGN = "DLT-LOG-CHANNEL-DESIGN"
    DLT_LOG_CHANNEL_DESIGN_TO_PROCESS_DESIGN_MAPPING = (
        "DLT-LOG-CHANNEL-DESIGN-TO-PROCESS-DESIGN-MAPPING"
    )
    DLT_LOG_CHANNEL_TO_PROCESS_MAPPING = "DLT-LOG-CHANNEL-TO-PROCESS-MAPPING"
    DOCUMENTATION = "DOCUMENTATION"
    E_2_E_PROFILE_COMPATIBILITY_PROPS = "E-2-E-PROFILE-COMPATIBILITY-PROPS"
    E_2_E_PROFILE_CONFIGURATION_SET = "E-2-E-PROFILE-CONFIGURATION-SET"
    ECU_ABSTRACTION_SW_COMPONENT_TYPE = "ECU-ABSTRACTION-SW-COMPONENT-TYPE"
    ECU_TIMING = "ECU-TIMING"
    ECUC_DEFINITION_COLLECTION = "ECUC-DEFINITION-COLLECTION"
    ECUC_DESTINATION_URI_DEF_SET = "ECUC-DESTINATION-URI-DEF-SET"
    ECUC_MODULE_CONFIGURATION_VALUES = "ECUC-MODULE-CONFIGURATION-VALUES"
    ECUC_MODULE_DEF = "ECUC-MODULE-DEF"
    ECUC_VALUE_COLLECTION = "ECUC-VALUE-COLLECTION"
    END_TO_END_PROTECTION_SET = "END-TO-END-PROTECTION-SET"
    ETH_IP_PROPS = "ETH-IP-PROPS"
    ETH_TCP_IP_ICMP_PROPS = "ETH-TCP-IP-ICMP-PROPS"
    ETH_TCP_IP_PROPS = "ETH-TCP-IP-PROPS"
    ETHERNET_RAW_DATA_STREAM_GRANT = "ETHERNET-RAW-DATA-STREAM-GRANT"
    ETHERNET_RAW_DATA_STREAM_MAPPING = "ETHERNET-RAW-DATA-STREAM-MAPPING"
    EVALUATED_VARIANT_SET = "EVALUATED-VARIANT-SET"
    EXECUTABLE = "EXECUTABLE"
    EXECUTABLE_TIMING = "EXECUTABLE-TIMING"
    FLAT_MAP = "FLAT-MAP"
    FM_FEATURE = "FM-FEATURE"
    FM_FEATURE_MAP = "FM-FEATURE-MAP"
    FM_FEATURE_MODEL = "FM-FEATURE-MODEL"
    FM_FEATURE_SELECTION_SET = "FM-FEATURE-SELECTION-SET"
    FUNCTION_GROUP_SET = "FUNCTION-GROUP-SET"
    FUNCTIONAL_CLUSTER_INTERACTS_WITH_FUNCTIONAL_CLUSTER_MAPPING = (
        "FUNCTIONAL-CLUSTER-INTERACTS-WITH-FUNCTIONAL-CLUSTER-MAPPING"
    )
    GENERAL_PURPOSE_CONNECTION = "GENERAL-PURPOSE-CONNECTION"
    GRANT = "GRANT"
    GRANT_DESIGN = "GRANT-DESIGN"
    HW_CATEGORY = "HW-CATEGORY"
    HW_ELEMENT = "HW-ELEMENT"
    HW_TYPE = "HW-TYPE"
    I_PV_6_EXT_HEADER_FILTER_SET = "I-PV-6-EXT-HEADER-FILTER-SET"
    IDS_COMMON_ELEMENT = "IDS-COMMON-ELEMENT"
    IDS_DESIGN = "IDS-DESIGN"
    IDS_MAPPING = "IDS-MAPPING"
    IDSM_INSTANCE = "IDSM-INSTANCE"
    IDSM_PROPERTIES = "IDSM-PROPERTIES"
    IMPLEMENTATION = "IMPLEMENTATION"
    IMPLEMENTATION_DATA_TYPE = "IMPLEMENTATION-DATA-TYPE"
    INTERFACE_MAPPING_SET = "INTERFACE-MAPPING-SET"
    INTERPOLATION_ROUTINE_MAPPING_SET = "INTERPOLATION-ROUTINE-MAPPING-SET"
    IP_IAM_REMOTE_SUBJECT = "IP-IAM-REMOTE-SUBJECT"
    IP_SEC_CONFIG_PROPS = "IP-SEC-CONFIG-PROPS"
    IP_SEC_IAM_REMOTE_SUBJECT = "IP-SEC-IAM-REMOTE-SUBJECT"
    J_1939_CONTROLLER_APPLICATION = "J-1939-CONTROLLER-APPLICATION"
    KEYWORD_SET = "KEYWORD-SET"
    LIFE_CYCLE_INFO_SET = "LIFE-CYCLE-INFO-SET"
    LIFE_CYCLE_STATE_DEFINITION_GROUP = "LIFE-CYCLE-STATE-DEFINITION-GROUP"
    MACHINE = "MACHINE"
    MACHINE_TIMING = "MACHINE-TIMING"
    MC_FUNCTION = "MC-FUNCTION"
    MC_GROUP = "MC-GROUP"
    MODE_DECLARATION_GROUP = "MODE-DECLARATION-GROUP"
    MODE_DECLARATION_MAPPING_SET = "MODE-DECLARATION-MAPPING-SET"
    MODE_SWITCH_INTERFACE = "MODE-SWITCH-INTERFACE"
    NV_BLOCK_SW_COMPONENT_TYPE = "NV-BLOCK-SW-COMPONENT-TYPE"
    NV_DATA_INTERFACE = "NV-DATA-INTERFACE"
    PARAMETER_INTERFACE = "PARAMETER-INTERFACE"
    PARAMETER_SW_COMPONENT_TYPE = "PARAMETER-SW-COMPONENT-TYPE"
    PERSISTENCY_DEPLOYMENT = "PERSISTENCY-DEPLOYMENT"
    PERSISTENCY_DEPLOYMENT_ELEMENT_TO_CRYPTO_KEY_SLOT_MAPPING = (
        "PERSISTENCY-DEPLOYMENT-ELEMENT-TO-CRYPTO-KEY-SLOT-MAPPING"
    )
    PERSISTENCY_DEPLOYMENT_TO_CRYPTO_KEY_SLOT_MAPPING = (
        "PERSISTENCY-DEPLOYMENT-TO-CRYPTO-KEY-SLOT-MAPPING"
    )
    PERSISTENCY_DEPLOYMENT_TO_DLT_LOG_CHANNEL_MAPPING = (
        "PERSISTENCY-DEPLOYMENT-TO-DLT-LOG-CHANNEL-MAPPING"
    )
    PERSISTENCY_FILE_STORAGE = "PERSISTENCY-FILE-STORAGE"
    PERSISTENCY_FILE_STORAGE_INTERFACE = "PERSISTENCY-FILE-STORAGE-INTERFACE"
    PERSISTENCY_INTERFACE = "PERSISTENCY-INTERFACE"
    PERSISTENCY_KEY_VALUE_STORAGE = "PERSISTENCY-KEY-VALUE-STORAGE"
    PERSISTENCY_KEY_VALUE_STORAGE_INTERFACE = (
        "PERSISTENCY-KEY-VALUE-STORAGE-INTERFACE"
    )
    PERSISTENCY_PORT_PROTOTYPE_TO_DEPLOYMENT_MAPPING = (
        "PERSISTENCY-PORT-PROTOTYPE-TO-DEPLOYMENT-MAPPING"
    )
    PERSISTENCY_PORT_PROTOTYPE_TO_FILE_STORAGE_MAPPING = (
        "PERSISTENCY-PORT-PROTOTYPE-TO-FILE-STORAGE-MAPPING"
    )
    PERSISTENCY_PORT_PROTOTYPE_TO_KEY_VALUE_STORAGE_MAPPING = (
        "PERSISTENCY-PORT-PROTOTYPE-TO-KEY-VALUE-STORAGE-MAPPING"
    )
    PHM_ABSTRACT_RECOVERY_NOTIFICATION_INTERFACE = (
        "PHM-ABSTRACT-RECOVERY-NOTIFICATION-INTERFACE"
    )
    PHM_CONTRIBUTION_TO_MACHINE_MAPPING = "PHM-CONTRIBUTION-TO-MACHINE-MAPPING"
    PHM_HEALTH_CHANNEL_INTERFACE = "PHM-HEALTH-CHANNEL-INTERFACE"
    PHM_HEALTH_CHANNEL_RECOVERY_NOTIFICATION_INTERFACE = (
        "PHM-HEALTH-CHANNEL-RECOVERY-NOTIFICATION-INTERFACE"
    )
    PHM_RECOVERY_ACTION_INTERFACE = "PHM-RECOVERY-ACTION-INTERFACE"
    PHM_SUPERVISED_ENTITY_INTERFACE = "PHM-SUPERVISED-ENTITY-INTERFACE"
    PHM_SUPERVISION_RECOVERY_NOTIFICATION_INTERFACE = (
        "PHM-SUPERVISION-RECOVERY-NOTIFICATION-INTERFACE"
    )
    PHYSICAL_DIMENSION = "PHYSICAL-DIMENSION"
    PHYSICAL_DIMENSION_MAPPING_SET = "PHYSICAL-DIMENSION-MAPPING-SET"
    PLATFORM_HEALTH_MANAGEMENT_CONTRIBUTION = (
        "PLATFORM-HEALTH-MANAGEMENT-CONTRIBUTION"
    )
    PLATFORM_HEALTH_MANAGEMENT_INTERFACE = (
        "PLATFORM-HEALTH-MANAGEMENT-INTERFACE"
    )
    PLATFORM_MODULE_ENDPOINT_CONFIGURATION = (
        "PLATFORM-MODULE-ENDPOINT-CONFIGURATION"
    )
    PLATFORM_MODULE_ETHERNET_ENDPOINT_CONFIGURATION = (
        "PLATFORM-MODULE-ETHERNET-ENDPOINT-CONFIGURATION"
    )
    PORT_INTERFACE = "PORT-INTERFACE"
    PORT_INTERFACE_MAPPING_SET = "PORT-INTERFACE-MAPPING-SET"
    PORT_INTERFACE_TO_DATA_TYPE_MAPPING = "PORT-INTERFACE-TO-DATA-TYPE-MAPPING"
    PORT_PROTOTYPE_BLUEPRINT = "PORT-PROTOTYPE-BLUEPRINT"
    POST_BUILD_VARIANT_CRITERION = "POST-BUILD-VARIANT-CRITERION"
    POST_BUILD_VARIANT_CRITERION_VALUE_SET = (
        "POST-BUILD-VARIANT-CRITERION-VALUE-SET"
    )
    PREDEFINED_VARIANT = "PREDEFINED-VARIANT"
    PROCESS = "PROCESS"
    PROCESS_DESIGN = "PROCESS-DESIGN"
    PROCESS_DESIGN_TO_MACHINE_DESIGN_MAPPING_SET = (
        "PROCESS-DESIGN-TO-MACHINE-DESIGN-MAPPING-SET"
    )
    PROCESS_EXECUTION_ERROR = "PROCESS-EXECUTION-ERROR"
    PROCESS_TO_MACHINE_MAPPING_SET = "PROCESS-TO-MACHINE-MAPPING-SET"
    PROVIDED_AP_SERVICE_INSTANCE = "PROVIDED-AP-SERVICE-INSTANCE"
    PROVIDED_SERVICE_INSTANCE_TO_SW_CLUSTER_DESIGN_P_PORT_PROTOTYPE_MAPPING = "PROVIDED-SERVICE-INSTANCE-TO-SW-CLUSTER-DESIGN-P-PORT-PROTOTYPE-MAPPING"
    PROVIDED_SOMEIP_SERVICE_INSTANCE = "PROVIDED-SOMEIP-SERVICE-INSTANCE"
    PROVIDED_USER_DEFINED_SERVICE_INSTANCE = (
        "PROVIDED-USER-DEFINED-SERVICE-INSTANCE"
    )
    RAPID_PROTOTYPING_SCENARIO = "RAPID-PROTOTYPING-SCENARIO"
    RAW_DATA_STREAM_CLIENT_INTERFACE = "RAW-DATA-STREAM-CLIENT-INTERFACE"
    RAW_DATA_STREAM_DEPLOYMENT = "RAW-DATA-STREAM-DEPLOYMENT"
    RAW_DATA_STREAM_GRANT = "RAW-DATA-STREAM-GRANT"
    RAW_DATA_STREAM_GRANT_DESIGN = "RAW-DATA-STREAM-GRANT-DESIGN"
    RAW_DATA_STREAM_MAPPING = "RAW-DATA-STREAM-MAPPING"
    RAW_DATA_STREAM_SERVER_INTERFACE = "RAW-DATA-STREAM-SERVER-INTERFACE"
    RECOVERY_NOTIFICATION_TO_P_PORT_PROTOTYPE_MAPPING = (
        "RECOVERY-NOTIFICATION-TO-P-PORT-PROTOTYPE-MAPPING"
    )
    REQUIRED_AP_SERVICE_INSTANCE = "REQUIRED-AP-SERVICE-INSTANCE"
    REQUIRED_SERVICE_INSTANCE_TO_SW_CLUSTER_DESIGN_R_PORT_PROTOTYPE_MAPPING = "REQUIRED-SERVICE-INSTANCE-TO-SW-CLUSTER-DESIGN-R-PORT-PROTOTYPE-MAPPING"
    REQUIRED_SOMEIP_SERVICE_INSTANCE = "REQUIRED-SOMEIP-SERVICE-INSTANCE"
    REQUIRED_USER_DEFINED_SERVICE_INSTANCE = (
        "REQUIRED-USER-DEFINED-SERVICE-INSTANCE"
    )
    REST_HTTP_PORT_PROTOTYPE_MAPPING = "REST-HTTP-PORT-PROTOTYPE-MAPPING"
    REST_SERVICE_INTERFACE = "REST-SERVICE-INTERFACE"
    SDG_DEF = "SDG-DEF"
    SECURE_COM_PROPS_SET = "SECURE-COM-PROPS-SET"
    SECURITY_EVENT_CONTEXT_MAPPING = "SECURITY-EVENT-CONTEXT-MAPPING"
    SECURITY_EVENT_CONTEXT_MAPPING_APPLICATION = (
        "SECURITY-EVENT-CONTEXT-MAPPING-APPLICATION"
    )
    SECURITY_EVENT_CONTEXT_MAPPING_BSW_MODULE = (
        "SECURITY-EVENT-CONTEXT-MAPPING-BSW-MODULE"
    )
    SECURITY_EVENT_CONTEXT_MAPPING_COMM_CONNECTOR = (
        "SECURITY-EVENT-CONTEXT-MAPPING-COMM-CONNECTOR"
    )
    SECURITY_EVENT_CONTEXT_MAPPING_FUNCTIONAL_CLUSTER = (
        "SECURITY-EVENT-CONTEXT-MAPPING-FUNCTIONAL-CLUSTER"
    )
    SECURITY_EVENT_DEFINITION = "SECURITY-EVENT-DEFINITION"
    SECURITY_EVENT_FILTER_CHAIN = "SECURITY-EVENT-FILTER-CHAIN"
    SECURITY_EVENT_MAPPING = "SECURITY-EVENT-MAPPING"
    SECURITY_EVENT_REPORT_INTERFACE = "SECURITY-EVENT-REPORT-INTERFACE"
    SECURITY_EVENT_REPORT_TO_SECURITY_EVENT_DEFINITION_MAPPING = (
        "SECURITY-EVENT-REPORT-TO-SECURITY-EVENT-DEFINITION-MAPPING"
    )
    SENDER_RECEIVER_INTERFACE = "SENDER-RECEIVER-INTERFACE"
    SENSOR_ACTUATOR_SW_COMPONENT_TYPE = "SENSOR-ACTUATOR-SW-COMPONENT-TYPE"
    SERIALIZATION_TECHNOLOGY = "SERIALIZATION-TECHNOLOGY"
    SERVICE_INSTANCE_TO_MACHINE_MAPPING = "SERVICE-INSTANCE-TO-MACHINE-MAPPING"
    SERVICE_INSTANCE_TO_PORT_PROTOTYPE_MAPPING = (
        "SERVICE-INSTANCE-TO-PORT-PROTOTYPE-MAPPING"
    )
    SERVICE_INSTANCE_TO_SIGNAL_MAPPING_SET = (
        "SERVICE-INSTANCE-TO-SIGNAL-MAPPING-SET"
    )
    SERVICE_INSTANCE_TO_SW_CLUSTER_DESIGN_PORT_PROTOTYPE_MAPPING = (
        "SERVICE-INSTANCE-TO-SW-CLUSTER-DESIGN-PORT-PROTOTYPE-MAPPING"
    )
    SERVICE_INTERFACE = "SERVICE-INTERFACE"
    SERVICE_INTERFACE_DEPLOYMENT = "SERVICE-INTERFACE-DEPLOYMENT"
    SERVICE_INTERFACE_MAPPING_SET = "SERVICE-INTERFACE-MAPPING-SET"
    SERVICE_INTERFACE_PEDIGREE = "SERVICE-INTERFACE-PEDIGREE"
    SERVICE_PROXY_SW_COMPONENT_TYPE = "SERVICE-PROXY-SW-COMPONENT-TYPE"
    SERVICE_SW_COMPONENT_TYPE = "SERVICE-SW-COMPONENT-TYPE"
    SERVICE_TIMING = "SERVICE-TIMING"
    SIGNAL_SERVICE_TRANSLATION_PROPS_SET = (
        "SIGNAL-SERVICE-TRANSLATION-PROPS-SET"
    )
    SOFTWARE_CLUSTER = "SOFTWARE-CLUSTER"
    SOFTWARE_CLUSTER_DESIGN = "SOFTWARE-CLUSTER-DESIGN"
    SOFTWARE_PACKAGE = "SOFTWARE-PACKAGE"
    SOMEIP_DATA_PROTOTYPE_TRANSFORMATION_PROPS = (
        "SOMEIP-DATA-PROTOTYPE-TRANSFORMATION-PROPS"
    )
    SOMEIP_SD_CLIENT_EVENT_GROUP_TIMING_CONFIG = (
        "SOMEIP-SD-CLIENT-EVENT-GROUP-TIMING-CONFIG"
    )
    SOMEIP_SD_CLIENT_SERVICE_INSTANCE_CONFIG = (
        "SOMEIP-SD-CLIENT-SERVICE-INSTANCE-CONFIG"
    )
    SOMEIP_SD_SERVER_EVENT_GROUP_TIMING_CONFIG = (
        "SOMEIP-SD-SERVER-EVENT-GROUP-TIMING-CONFIG"
    )
    SOMEIP_SD_SERVER_SERVICE_INSTANCE_CONFIG = (
        "SOMEIP-SD-SERVER-SERVICE-INSTANCE-CONFIG"
    )
    SOMEIP_SERVICE_INSTANCE_TO_MACHINE_MAPPING = (
        "SOMEIP-SERVICE-INSTANCE-TO-MACHINE-MAPPING"
    )
    SOMEIP_SERVICE_INTERFACE_DEPLOYMENT = "SOMEIP-SERVICE-INTERFACE-DEPLOYMENT"
    STARTUP_CONFIG_SET = "STARTUP-CONFIG-SET"
    STD_CPP_IMPLEMENTATION_DATA_TYPE = "STD-CPP-IMPLEMENTATION-DATA-TYPE"
    SW_ADDR_METHOD = "SW-ADDR-METHOD"
    SW_AXIS_TYPE = "SW-AXIS-TYPE"
    SW_BASE_TYPE = "SW-BASE-TYPE"
    SW_COMPONENT_TYPE = "SW-COMPONENT-TYPE"
    SW_RECORD_LAYOUT = "SW-RECORD-LAYOUT"
    SW_SYSTEMCONST = "SW-SYSTEMCONST"
    SW_SYSTEMCONSTANT_VALUE_SET = "SW-SYSTEMCONSTANT-VALUE-SET"
    SWC_BSW_MAPPING = "SWC-BSW-MAPPING"
    SWC_IMPLEMENTATION = "SWC-IMPLEMENTATION"
    SWC_TIMING = "SWC-TIMING"
    SYNCHRONIZED_TIME_BASE_CONSUMER_INTERFACE = (
        "SYNCHRONIZED-TIME-BASE-CONSUMER-INTERFACE"
    )
    SYNCHRONIZED_TIME_BASE_PROVIDER_INTERFACE = (
        "SYNCHRONIZED-TIME-BASE-PROVIDER-INTERFACE"
    )
    SYSTEM = "SYSTEM"
    SYSTEM_SIGNAL = "SYSTEM-SIGNAL"
    SYSTEM_SIGNAL_GROUP = "SYSTEM-SIGNAL-GROUP"
    SYSTEM_TIMING = "SYSTEM-TIMING"
    TCP_OPTION_FILTER_SET = "TCP-OPTION-FILTER-SET"
    TD_CP_SOFTWARE_CLUSTER_MAPPING_SET = "TD-CP-SOFTWARE-CLUSTER-MAPPING-SET"
    TIME_BASE_PROVIDER_TO_PERSISTENCY_MAPPING = (
        "TIME-BASE-PROVIDER-TO-PERSISTENCY-MAPPING"
    )
    TIME_SYNC_PORT_PROTOTYPE_TO_TIME_BASE_MAPPING = (
        "TIME-SYNC-PORT-PROTOTYPE-TO-TIME-BASE-MAPPING"
    )
    TIMING_EXTENSION = "TIMING-EXTENSION"
    TLS_IAM_REMOTE_SUBJECT = "TLS-IAM-REMOTE-SUBJECT"
    TLV_DATA_ID_DEFINITION_SET = "TLV-DATA-ID-DEFINITION-SET"
    TRANSFORMATION_PROPS_SET = "TRANSFORMATION-PROPS-SET"
    TRANSFORMATION_PROPS_TO_SERVICE_INTERFACE_ELEMENT_MAPPING_SET = (
        "TRANSFORMATION-PROPS-TO-SERVICE-INTERFACE-ELEMENT-MAPPING-SET"
    )
    TRIGGER_INTERFACE = "TRIGGER-INTERFACE"
    UNIT = "UNIT"
    UNIT_GROUP = "UNIT-GROUP"
    UPLOADABLE_EXCLUSIVE_PACKAGE_ELEMENT = (
        "UPLOADABLE-EXCLUSIVE-PACKAGE-ELEMENT"
    )
    UPLOADABLE_PACKAGE_ELEMENT = "UPLOADABLE-PACKAGE-ELEMENT"
    USER_DEFINED_SERVICE_INSTANCE_TO_MACHINE_MAPPING = (
        "USER-DEFINED-SERVICE-INSTANCE-TO-MACHINE-MAPPING"
    )
    USER_DEFINED_SERVICE_INTERFACE_DEPLOYMENT = (
        "USER-DEFINED-SERVICE-INTERFACE-DEPLOYMENT"
    )
    VEHICLE_PACKAGE = "VEHICLE-PACKAGE"
    VFB_TIMING = "VFB-TIMING"
    VIEW_MAP_SET = "VIEW-MAP-SET"
