from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class AtpPrototypeSubtypesEnum(Enum):
    ABSTRACT_PROVIDED_PORT_PROTOTYPE = "ABSTRACT-PROVIDED-PORT-PROTOTYPE"
    ABSTRACT_REQUIRED_PORT_PROTOTYPE = "ABSTRACT-REQUIRED-PORT-PROTOTYPE"
    APPLICATION_ARRAY_ELEMENT = "APPLICATION-ARRAY-ELEMENT"
    APPLICATION_ASSOC_MAP_ELEMENT = "APPLICATION-ASSOC-MAP-ELEMENT"
    APPLICATION_COMPOSITE_ELEMENT_DATA_PROTOTYPE = "APPLICATION-COMPOSITE-ELEMENT-DATA-PROTOTYPE"
    APPLICATION_RECORD_ELEMENT = "APPLICATION-RECORD-ELEMENT"
    ARGUMENT_DATA_PROTOTYPE = "ARGUMENT-DATA-PROTOTYPE"
    ATP_PROTOTYPE = "ATP-PROTOTYPE"
    AUTOSAR_DATA_PROTOTYPE = "AUTOSAR-DATA-PROTOTYPE"
    DATA_PROTOTYPE = "DATA-PROTOTYPE"
    FIELD_VALUE = "FIELD"
    MODE_DECLARATION_GROUP_PROTOTYPE = "MODE-DECLARATION-GROUP-PROTOTYPE"
    P_PORT_PROTOTYPE = "P-PORT-PROTOTYPE"
    PARAMETER_DATA_PROTOTYPE = "PARAMETER-DATA-PROTOTYPE"
    PERSISTENCY_DATA_ELEMENT = "PERSISTENCY-DATA-ELEMENT"
    PORT_PROTOTYPE = "PORT-PROTOTYPE"
    PR_PORT_PROTOTYPE = "PR-PORT-PROTOTYPE"
    R_PORT_PROTOTYPE = "R-PORT-PROTOTYPE"
    ROOT_SW_CLUSTER_DESIGN_COMPONENT_PROTOTYPE = "ROOT-SW-CLUSTER-DESIGN-COMPONENT-PROTOTYPE"
    ROOT_SW_COMPONENT_PROTOTYPE = "ROOT-SW-COMPONENT-PROTOTYPE"
    ROOT_SW_COMPOSITION_PROTOTYPE = "ROOT-SW-COMPOSITION-PROTOTYPE"
    SW_COMPONENT_PROTOTYPE = "SW-COMPONENT-PROTOTYPE"
    VARIABLE_DATA_PROTOTYPE = "VARIABLE-DATA-PROTOTYPE"
