from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class AtpBlueprintableSubtypesEnum(Enum):
    ABSTRACT_IMPLEMENTATION_DATA_TYPE = "ABSTRACT-IMPLEMENTATION-DATA-TYPE"
    ABSTRACT_PROVIDED_PORT_PROTOTYPE = "ABSTRACT-PROVIDED-PORT-PROTOTYPE"
    ABSTRACT_RAW_DATA_STREAM_INTERFACE = "ABSTRACT-RAW-DATA-STREAM-INTERFACE"
    ABSTRACT_REQUIRED_PORT_PROTOTYPE = "ABSTRACT-REQUIRED-PORT-PROTOTYPE"
    ABSTRACT_SYNCHRONIZED_TIME_BASE_INTERFACE = (
        "ABSTRACT-SYNCHRONIZED-TIME-BASE-INTERFACE"
    )
    ACL_OBJECT_SET = "ACL-OBJECT-SET"
    ACL_OPERATION = "ACL-OPERATION"
    ACL_PERMISSION = "ACL-PERMISSION"
    ACL_ROLE = "ACL-ROLE"
    ADAPTIVE_APPLICATION_SW_COMPONENT_TYPE = (
        "ADAPTIVE-APPLICATION-SW-COMPONENT-TYPE"
    )
    ALIAS_NAME_SET = "ALIAS-NAME-SET"
    APPLICATION_ARRAY_DATA_TYPE = "APPLICATION-ARRAY-DATA-TYPE"
    APPLICATION_ASSOC_MAP_DATA_TYPE = "APPLICATION-ASSOC-MAP-DATA-TYPE"
    APPLICATION_COMPOSITE_DATA_TYPE = "APPLICATION-COMPOSITE-DATA-TYPE"
    APPLICATION_DATA_TYPE = "APPLICATION-DATA-TYPE"
    APPLICATION_DEFERRED_DATA_TYPE = "APPLICATION-DEFERRED-DATA-TYPE"
    APPLICATION_PRIMITIVE_DATA_TYPE = "APPLICATION-PRIMITIVE-DATA-TYPE"
    APPLICATION_RECORD_DATA_TYPE = "APPLICATION-RECORD-DATA-TYPE"
    APPLICATION_SW_COMPONENT_TYPE = "APPLICATION-SW-COMPONENT-TYPE"
    AR_PACKAGE = "AR-PACKAGE"
    ATOMIC_SW_COMPONENT_TYPE = "ATOMIC-SW-COMPONENT-TYPE"
    ATP_BLUEPRINTABLE = "ATP-BLUEPRINTABLE"
    BSW_ENTRY_RELATIONSHIP_SET = "BSW-ENTRY-RELATIONSHIP-SET"
    BSW_MODULE_DESCRIPTION = "BSW-MODULE-DESCRIPTION"
    BSW_MODULE_ENTRY = "BSW-MODULE-ENTRY"
    BUILD_ACTION = "BUILD-ACTION"
    BUILD_ACTION_ENTITY = "BUILD-ACTION-ENTITY"
    BUILD_ACTION_ENVIRONMENT = "BUILD-ACTION-ENVIRONMENT"
    BUILD_ACTION_MANIFEST = "BUILD-ACTION-MANIFEST"
    CLIENT_SERVER_INTERFACE = "CLIENT-SERVER-INTERFACE"
    CLIENT_SERVER_INTERFACE_MAPPING = "CLIENT-SERVER-INTERFACE-MAPPING"
    COMPLEX_DEVICE_DRIVER_SW_COMPONENT_TYPE = (
        "COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE"
    )
    COMPOSITE_INTERFACE = "COMPOSITE-INTERFACE"
    COMPOSITION_SW_COMPONENT_TYPE = "COMPOSITION-SW-COMPONENT-TYPE"
    COMPU_METHOD = "COMPU-METHOD"
    CONSISTENCY_NEEDS = "CONSISTENCY-NEEDS"
    CPP_IMPLEMENTATION_DATA_TYPE = "CPP-IMPLEMENTATION-DATA-TYPE"
    CRYPTO_CERTIFICATE_INTERFACE = "CRYPTO-CERTIFICATE-INTERFACE"
    CRYPTO_INTERFACE = "CRYPTO-INTERFACE"
    CRYPTO_KEY_SLOT_INTERFACE = "CRYPTO-KEY-SLOT-INTERFACE"
    CRYPTO_PROVIDER_INTERFACE = "CRYPTO-PROVIDER-INTERFACE"
    CRYPTO_TRUST_MASTER_INTERFACE = "CRYPTO-TRUST-MASTER-INTERFACE"
    CUSTOM_CPP_IMPLEMENTATION_DATA_TYPE = "CUSTOM-CPP-IMPLEMENTATION-DATA-TYPE"
    DATA_CONSTR = "DATA-CONSTR"
    DATA_INTERFACE = "DATA-INTERFACE"
    DATA_TYPE_MAPPING_SET = "DATA-TYPE-MAPPING-SET"
    DIAGNOSTIC_ABSTRACT_DATA_IDENTIFIER_INTERFACE = (
        "DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER-INTERFACE"
    )
    DIAGNOSTIC_ABSTRACT_ROUTINE_INTERFACE = (
        "DIAGNOSTIC-ABSTRACT-ROUTINE-INTERFACE"
    )
    DIAGNOSTIC_CONDITION_INTERFACE = "DIAGNOSTIC-CONDITION-INTERFACE"
    DIAGNOSTIC_DATA_ELEMENT_INTERFACE = "DIAGNOSTIC-DATA-ELEMENT-INTERFACE"
    DIAGNOSTIC_DATA_IDENTIFIER_GENERIC_INTERFACE = (
        "DIAGNOSTIC-DATA-IDENTIFIER-GENERIC-INTERFACE"
    )
    DIAGNOSTIC_DATA_IDENTIFIER_INTERFACE = (
        "DIAGNOSTIC-DATA-IDENTIFIER-INTERFACE"
    )
    DIAGNOSTIC_DO_IP_ACTIVATION_LINE_INTERFACE = (
        "DIAGNOSTIC-DO-IP-ACTIVATION-LINE-INTERFACE"
    )
    DIAGNOSTIC_DO_IP_GROUP_IDENTIFICATION_INTERFACE = (
        "DIAGNOSTIC-DO-IP-GROUP-IDENTIFICATION-INTERFACE"
    )
    DIAGNOSTIC_DO_IP_POWER_MODE_INTERFACE = (
        "DIAGNOSTIC-DO-IP-POWER-MODE-INTERFACE"
    )
    DIAGNOSTIC_DO_IP_TRIGGER_VEHICLE_ANNOUNCEMENT_INTERFACE = (
        "DIAGNOSTIC-DO-IP-TRIGGER-VEHICLE-ANNOUNCEMENT-INTERFACE"
    )
    DIAGNOSTIC_DOWNLOAD_INTERFACE = "DIAGNOSTIC-DOWNLOAD-INTERFACE"
    DIAGNOSTIC_DTC_INFORMATION_INTERFACE = (
        "DIAGNOSTIC-DTC-INFORMATION-INTERFACE"
    )
    DIAGNOSTIC_ECU_RESET_INTERFACE = "DIAGNOSTIC-ECU-RESET-INTERFACE"
    DIAGNOSTIC_EVENT_INTERFACE = "DIAGNOSTIC-EVENT-INTERFACE"
    DIAGNOSTIC_GENERIC_UDS_INTERFACE = "DIAGNOSTIC-GENERIC-UDS-INTERFACE"
    DIAGNOSTIC_INDICATOR_INTERFACE = "DIAGNOSTIC-INDICATOR-INTERFACE"
    DIAGNOSTIC_MONITOR_INTERFACE = "DIAGNOSTIC-MONITOR-INTERFACE"
    DIAGNOSTIC_OPERATION_CYCLE_INTERFACE = (
        "DIAGNOSTIC-OPERATION-CYCLE-INTERFACE"
    )
    DIAGNOSTIC_PORT_INTERFACE = "DIAGNOSTIC-PORT-INTERFACE"
    DIAGNOSTIC_ROUTINE_GENERIC_INTERFACE = (
        "DIAGNOSTIC-ROUTINE-GENERIC-INTERFACE"
    )
    DIAGNOSTIC_ROUTINE_INTERFACE = "DIAGNOSTIC-ROUTINE-INTERFACE"
    DIAGNOSTIC_SECURITY_LEVEL_INTERFACE = "DIAGNOSTIC-SECURITY-LEVEL-INTERFACE"
    DIAGNOSTIC_SERVICE_VALIDATION_INTERFACE = (
        "DIAGNOSTIC-SERVICE-VALIDATION-INTERFACE"
    )
    DIAGNOSTIC_UPLOAD_INTERFACE = "DIAGNOSTIC-UPLOAD-INTERFACE"
    ECU_ABSTRACTION_SW_COMPONENT_TYPE = "ECU-ABSTRACTION-SW-COMPONENT-TYPE"
    ECUC_DEFINITION_COLLECTION = "ECUC-DEFINITION-COLLECTION"
    ECUC_DESTINATION_URI_DEF_SET = "ECUC-DESTINATION-URI-DEF-SET"
    ECUC_MODULE_DEF = "ECUC-MODULE-DEF"
    FLAT_MAP = "FLAT-MAP"
    IMPLEMENTATION_DATA_TYPE = "IMPLEMENTATION-DATA-TYPE"
    KEYWORD_SET = "KEYWORD-SET"
    LIFE_CYCLE_STATE = "LIFE-CYCLE-STATE"
    LIFE_CYCLE_STATE_DEFINITION_GROUP = "LIFE-CYCLE-STATE-DEFINITION-GROUP"
    MODE_DECLARATION_GROUP = "MODE-DECLARATION-GROUP"
    MODE_INTERFACE_MAPPING = "MODE-INTERFACE-MAPPING"
    MODE_SWITCH_INTERFACE = "MODE-SWITCH-INTERFACE"
    NV_BLOCK_SW_COMPONENT_TYPE = "NV-BLOCK-SW-COMPONENT-TYPE"
    NV_DATA_INTERFACE = "NV-DATA-INTERFACE"
    P_PORT_PROTOTYPE = "P-PORT-PROTOTYPE"
    PARAMETER_INTERFACE = "PARAMETER-INTERFACE"
    PARAMETER_SW_COMPONENT_TYPE = "PARAMETER-SW-COMPONENT-TYPE"
    PERSISTENCY_FILE_STORAGE_INTERFACE = "PERSISTENCY-FILE-STORAGE-INTERFACE"
    PERSISTENCY_INTERFACE = "PERSISTENCY-INTERFACE"
    PERSISTENCY_KEY_VALUE_STORAGE_INTERFACE = (
        "PERSISTENCY-KEY-VALUE-STORAGE-INTERFACE"
    )
    PHM_ABSTRACT_RECOVERY_NOTIFICATION_INTERFACE = (
        "PHM-ABSTRACT-RECOVERY-NOTIFICATION-INTERFACE"
    )
    PHM_HEALTH_CHANNEL_INTERFACE = "PHM-HEALTH-CHANNEL-INTERFACE"
    PHM_HEALTH_CHANNEL_RECOVERY_NOTIFICATION_INTERFACE = (
        "PHM-HEALTH-CHANNEL-RECOVERY-NOTIFICATION-INTERFACE"
    )
    PHM_RECOVERY_ACTION_INTERFACE = "PHM-RECOVERY-ACTION-INTERFACE"
    PHM_SUPERVISED_ENTITY_INTERFACE = "PHM-SUPERVISED-ENTITY-INTERFACE"
    PHM_SUPERVISION_RECOVERY_NOTIFICATION_INTERFACE = (
        "PHM-SUPERVISION-RECOVERY-NOTIFICATION-INTERFACE"
    )
    PLATFORM_HEALTH_MANAGEMENT_INTERFACE = (
        "PLATFORM-HEALTH-MANAGEMENT-INTERFACE"
    )
    PORT_INTERFACE = "PORT-INTERFACE"
    PORT_INTERFACE_MAPPING = "PORT-INTERFACE-MAPPING"
    PORT_INTERFACE_MAPPING_SET = "PORT-INTERFACE-MAPPING-SET"
    PORT_PROTOTYPE = "PORT-PROTOTYPE"
    PR_PORT_PROTOTYPE = "PR-PORT-PROTOTYPE"
    R_PORT_PROTOTYPE = "R-PORT-PROTOTYPE"
    RAW_DATA_STREAM_CLIENT_INTERFACE = "RAW-DATA-STREAM-CLIENT-INTERFACE"
    RAW_DATA_STREAM_SERVER_INTERFACE = "RAW-DATA-STREAM-SERVER-INTERFACE"
    REST_ABSTRACT_ENDPOINT = "REST-ABSTRACT-ENDPOINT"
    REST_ENDPOINT_DELETE = "REST-ENDPOINT-DELETE"
    REST_ENDPOINT_GET = "REST-ENDPOINT-GET"
    REST_ENDPOINT_POST = "REST-ENDPOINT-POST"
    REST_ENDPOINT_PUT = "REST-ENDPOINT-PUT"
    REST_SERVICE_INTERFACE = "REST-SERVICE-INTERFACE"
    SECURITY_EVENT_REPORT_INTERFACE = "SECURITY-EVENT-REPORT-INTERFACE"
    SENDER_RECEIVER_INTERFACE = "SENDER-RECEIVER-INTERFACE"
    SENSOR_ACTUATOR_SW_COMPONENT_TYPE = "SENSOR-ACTUATOR-SW-COMPONENT-TYPE"
    SERVICE_INTERFACE = "SERVICE-INTERFACE"
    SERVICE_PROXY_SW_COMPONENT_TYPE = "SERVICE-PROXY-SW-COMPONENT-TYPE"
    SERVICE_SW_COMPONENT_TYPE = "SERVICE-SW-COMPONENT-TYPE"
    STD_CPP_IMPLEMENTATION_DATA_TYPE = "STD-CPP-IMPLEMENTATION-DATA-TYPE"
    SW_ADDR_METHOD = "SW-ADDR-METHOD"
    SW_BASE_TYPE = "SW-BASE-TYPE"
    SW_COMPONENT_TYPE = "SW-COMPONENT-TYPE"
    SYNCHRONIZED_TIME_BASE_CONSUMER_INTERFACE = (
        "SYNCHRONIZED-TIME-BASE-CONSUMER-INTERFACE"
    )
    SYNCHRONIZED_TIME_BASE_PROVIDER_INTERFACE = (
        "SYNCHRONIZED-TIME-BASE-PROVIDER-INTERFACE"
    )
    TRIGGER_INTERFACE = "TRIGGER-INTERFACE"
    TRIGGER_INTERFACE_MAPPING = "TRIGGER-INTERFACE-MAPPING"
    VARIABLE_AND_PARAMETER_INTERFACE_MAPPING = (
        "VARIABLE-AND-PARAMETER-INTERFACE-MAPPING"
    )
    VFB_TIMING = "VFB-TIMING"
