from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class CommunicationClusterSubtypesEnum(Enum):
    ABSTRACT_CAN_CLUSTER = "ABSTRACT-CAN-CLUSTER"
    CAN_CLUSTER = "CAN-CLUSTER"
    COMMUNICATION_CLUSTER = "COMMUNICATION-CLUSTER"
    ETHERNET_CLUSTER = "ETHERNET-CLUSTER"
    FLEXRAY_CLUSTER = "FLEXRAY-CLUSTER"
    J_1939_CLUSTER = "J-1939-CLUSTER"
    LIN_CLUSTER = "LIN-CLUSTER"
    TTCAN_CLUSTER = "TTCAN-CLUSTER"
    USER_DEFINED_CLUSTER = "USER-DEFINED-CLUSTER"
