from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class CommunicationControllerSubtypesEnum(Enum):
    ABSTRACT_CAN_COMMUNICATION_CONTROLLER = (
        "ABSTRACT-CAN-COMMUNICATION-CONTROLLER"
    )
    CAN_COMMUNICATION_CONTROLLER = "CAN-COMMUNICATION-CONTROLLER"
    COMMUNICATION_CONTROLLER = "COMMUNICATION-CONTROLLER"
    ETHERNET_COMMUNICATION_CONTROLLER = "ETHERNET-COMMUNICATION-CONTROLLER"
    FLEXRAY_COMMUNICATION_CONTROLLER = "FLEXRAY-COMMUNICATION-CONTROLLER"
    LIN_COMMUNICATION_CONTROLLER = "LIN-COMMUNICATION-CONTROLLER"
    LIN_MASTER = "LIN-MASTER"
    LIN_SLAVE = "LIN-SLAVE"
    TTCAN_COMMUNICATION_CONTROLLER = "TTCAN-COMMUNICATION-CONTROLLER"
    USER_DEFINED_COMMUNICATION_CONTROLLER = (
        "USER-DEFINED-COMMUNICATION-CONTROLLER"
    )
