from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class CppImplementationDataTypeContextTargetSubtypesEnum(Enum):
    CPP_IMPLEMENTATION_DATA_TYPE = "CPP-IMPLEMENTATION-DATA-TYPE"
    CPP_IMPLEMENTATION_DATA_TYPE_CONTEXT_TARGET = (
        "CPP-IMPLEMENTATION-DATA-TYPE-CONTEXT-TARGET"
    )
    CPP_IMPLEMENTATION_DATA_TYPE_ELEMENT = (
        "CPP-IMPLEMENTATION-DATA-TYPE-ELEMENT"
    )
    CUSTOM_CPP_IMPLEMENTATION_DATA_TYPE = "CUSTOM-CPP-IMPLEMENTATION-DATA-TYPE"
    STD_CPP_IMPLEMENTATION_DATA_TYPE = "STD-CPP-IMPLEMENTATION-DATA-TYPE"
