from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class DataFormatElementReferenceSubtypesEnum(Enum):
    ABSTRACT_CLASS_TAILORING = "ABSTRACT-CLASS-TAILORING"
    AGGREGATION_TAILORING = "AGGREGATION-TAILORING"
    ATTRIBUTE_TAILORING = "ATTRIBUTE-TAILORING"
    CONCRETE_CLASS_TAILORING = "CONCRETE-CLASS-TAILORING"
    CONSTRAINT_TAILORING = "CONSTRAINT-TAILORING"
    DATA_FORMAT_ELEMENT_REFERENCE = "DATA-FORMAT-ELEMENT-REFERENCE"
    DATA_FORMAT_ELEMENT_SCOPE = "DATA-FORMAT-ELEMENT-SCOPE"
    PRIMITIVE_ATTRIBUTE_TAILORING = "PRIMITIVE-ATTRIBUTE-TAILORING"
    REFERENCE_TAILORING = "REFERENCE-TAILORING"
    SDG_TAILORING = "SDG-TAILORING"
