from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class DataInterfaceSubtypesEnum(Enum):
    DATA_INTERFACE = "DATA-INTERFACE"
    NV_DATA_INTERFACE = "NV-DATA-INTERFACE"
    PARAMETER_INTERFACE = "PARAMETER-INTERFACE"
    SENDER_RECEIVER_INTERFACE = "SENDER-RECEIVER-INTERFACE"
