from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class DataPrototypeSubtypesEnum(Enum):
    APPLICATION_ARRAY_ELEMENT = "APPLICATION-ARRAY-ELEMENT"
    APPLICATION_ASSOC_MAP_ELEMENT = "APPLICATION-ASSOC-MAP-ELEMENT"
    APPLICATION_COMPOSITE_ELEMENT_DATA_PROTOTYPE = (
        "APPLICATION-COMPOSITE-ELEMENT-DATA-PROTOTYPE"
    )
    APPLICATION_RECORD_ELEMENT = "APPLICATION-RECORD-ELEMENT"
    ARGUMENT_DATA_PROTOTYPE = "ARGUMENT-DATA-PROTOTYPE"
    AUTOSAR_DATA_PROTOTYPE = "AUTOSAR-DATA-PROTOTYPE"
    DATA_PROTOTYPE = "DATA-PROTOTYPE"
    FIELD = "FIELD"
    PARAMETER_DATA_PROTOTYPE = "PARAMETER-DATA-PROTOTYPE"
    PERSISTENCY_DATA_ELEMENT = "PERSISTENCY-DATA-ELEMENT"
    VARIABLE_DATA_PROTOTYPE = "VARIABLE-DATA-PROTOTYPE"
