from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class DiagnosticAbstractDataIdentifierSubtypesEnum(Enum):
    DIAGNOSTIC_ABSTRACT_DATA_IDENTIFIER = "DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER"
    DIAGNOSTIC_DATA_IDENTIFIER = "DIAGNOSTIC-DATA-IDENTIFIER"
    DIAGNOSTIC_DYNAMIC_DATA_IDENTIFIER = "DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER"
