from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class DiagnosticTroubleCodeSubtypesEnum(Enum):
    DIAGNOSTIC_TROUBLE_CODE = "DIAGNOSTIC-TROUBLE-CODE"
    DIAGNOSTIC_TROUBLE_CODE_J_1939 = "DIAGNOSTIC-TROUBLE-CODE-J-1939"
    DIAGNOSTIC_TROUBLE_CODE_OBD = "DIAGNOSTIC-TROUBLE-CODE-OBD"
    DIAGNOSTIC_TROUBLE_CODE_UDS = "DIAGNOSTIC-TROUBLE-CODE-UDS"
