from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class EcucParameterDefSubtypesEnum(Enum):
    ECUC_ABSTRACT_STRING_PARAM_DEF = "ECUC-ABSTRACT-STRING-PARAM-DEF"
    ECUC_ADD_INFO_PARAM_DEF = "ECUC-ADD-INFO-PARAM-DEF"
    ECUC_BOOLEAN_PARAM_DEF = "ECUC-BOOLEAN-PARAM-DEF"
    ECUC_ENUMERATION_PARAM_DEF = "ECUC-ENUMERATION-PARAM-DEF"
    ECUC_FLOAT_PARAM_DEF = "ECUC-FLOAT-PARAM-DEF"
    ECUC_FUNCTION_NAME_DEF = "ECUC-FUNCTION-NAME-DEF"
    ECUC_INTEGER_PARAM_DEF = "ECUC-INTEGER-PARAM-DEF"
    ECUC_LINKER_SYMBOL_DEF = "ECUC-LINKER-SYMBOL-DEF"
    ECUC_MULTILINE_STRING_PARAM_DEF = "ECUC-MULTILINE-STRING-PARAM-DEF"
    ECUC_PARAMETER_DEF = "ECUC-PARAMETER-DEF"
    ECUC_STRING_PARAM_DEF = "ECUC-STRING-PARAM-DEF"
