from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class EcucAbstractReferenceDefSubtypesEnum(Enum):
    ECUC_ABSTRACT_EXTERNAL_REFERENCE_DEF = (
        "ECUC-ABSTRACT-EXTERNAL-REFERENCE-DEF"
    )
    ECUC_ABSTRACT_INTERNAL_REFERENCE_DEF = (
        "ECUC-ABSTRACT-INTERNAL-REFERENCE-DEF"
    )
    ECUC_ABSTRACT_REFERENCE_DEF = "ECUC-ABSTRACT-REFERENCE-DEF"
    ECUC_CHOICE_REFERENCE_DEF = "ECUC-CHOICE-REFERENCE-DEF"
    ECUC_FOREIGN_REFERENCE_DEF = "ECUC-FOREIGN-REFERENCE-DEF"
    ECUC_INSTANCE_REFERENCE_DEF = "ECUC-INSTANCE-REFERENCE-DEF"
    ECUC_REFERENCE_DEF = "ECUC-REFERENCE-DEF"
    ECUC_SYMBOLIC_NAME_REFERENCE_DEF = "ECUC-SYMBOLIC-NAME-REFERENCE-DEF"
    ECUC_URI_REFERENCE_DEF = "ECUC-URI-REFERENCE-DEF"
