from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class EcucDefinitionElementSubtypesEnum(Enum):
    ECUC_ABSTRACT_EXTERNAL_REFERENCE_DEF = (
        "ECUC-ABSTRACT-EXTERNAL-REFERENCE-DEF"
    )
    ECUC_ABSTRACT_INTERNAL_REFERENCE_DEF = (
        "ECUC-ABSTRACT-INTERNAL-REFERENCE-DEF"
    )
    ECUC_ABSTRACT_REFERENCE_DEF = "ECUC-ABSTRACT-REFERENCE-DEF"
    ECUC_ABSTRACT_STRING_PARAM_DEF = "ECUC-ABSTRACT-STRING-PARAM-DEF"
    ECUC_ADD_INFO_PARAM_DEF = "ECUC-ADD-INFO-PARAM-DEF"
    ECUC_BOOLEAN_PARAM_DEF = "ECUC-BOOLEAN-PARAM-DEF"
    ECUC_CHOICE_CONTAINER_DEF = "ECUC-CHOICE-CONTAINER-DEF"
    ECUC_CHOICE_REFERENCE_DEF = "ECUC-CHOICE-REFERENCE-DEF"
    ECUC_COMMON_ATTRIBUTES = "ECUC-COMMON-ATTRIBUTES"
    ECUC_CONTAINER_DEF = "ECUC-CONTAINER-DEF"
    ECUC_DEFINITION_ELEMENT = "ECUC-DEFINITION-ELEMENT"
    ECUC_ENUMERATION_PARAM_DEF = "ECUC-ENUMERATION-PARAM-DEF"
    ECUC_FLOAT_PARAM_DEF = "ECUC-FLOAT-PARAM-DEF"
    ECUC_FOREIGN_REFERENCE_DEF = "ECUC-FOREIGN-REFERENCE-DEF"
    ECUC_FUNCTION_NAME_DEF = "ECUC-FUNCTION-NAME-DEF"
    ECUC_INSTANCE_REFERENCE_DEF = "ECUC-INSTANCE-REFERENCE-DEF"
    ECUC_INTEGER_PARAM_DEF = "ECUC-INTEGER-PARAM-DEF"
    ECUC_LINKER_SYMBOL_DEF = "ECUC-LINKER-SYMBOL-DEF"
    ECUC_MODULE_DEF = "ECUC-MODULE-DEF"
    ECUC_MULTILINE_STRING_PARAM_DEF = "ECUC-MULTILINE-STRING-PARAM-DEF"
    ECUC_PARAM_CONF_CONTAINER_DEF = "ECUC-PARAM-CONF-CONTAINER-DEF"
    ECUC_PARAMETER_DEF = "ECUC-PARAMETER-DEF"
    ECUC_REFERENCE_DEF = "ECUC-REFERENCE-DEF"
    ECUC_STRING_PARAM_DEF = "ECUC-STRING-PARAM-DEF"
    ECUC_SYMBOLIC_NAME_REFERENCE_DEF = "ECUC-SYMBOLIC-NAME-REFERENCE-DEF"
    ECUC_URI_REFERENCE_DEF = "ECUC-URI-REFERENCE-DEF"
