from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class EocExecutableEntityRefAbstractSubtypesEnum(Enum):
    EOC_EVENT_REF = "EOC-EVENT-REF"
    EOC_EXECUTABLE_ENTITY_REF = "EOC-EXECUTABLE-ENTITY-REF"
    EOC_EXECUTABLE_ENTITY_REF_ABSTRACT = "EOC-EXECUTABLE-ENTITY-REF-ABSTRACT"
    EOC_EXECUTABLE_ENTITY_REF_GROUP = "EOC-EXECUTABLE-ENTITY-REF-GROUP"
