from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class FrameSubtypesEnum(Enum):
    ABSTRACT_ETHERNET_FRAME = "ABSTRACT-ETHERNET-FRAME"
    CAN_FRAME = "CAN-FRAME"
    ETHERNET_FRAME = "ETHERNET-FRAME"
    FLEXRAY_FRAME = "FLEXRAY-FRAME"
    FRAME = "FRAME"
    GENERIC_ETHERNET_FRAME = "GENERIC-ETHERNET-FRAME"
    IEEE_1722_TP_ETHERNET_FRAME = "IEEE-1722-TP-ETHERNET-FRAME"
    LIN_EVENT_TRIGGERED_FRAME = "LIN-EVENT-TRIGGERED-FRAME"
    LIN_FRAME = "LIN-FRAME"
    LIN_SPORADIC_FRAME = "LIN-SPORADIC-FRAME"
    LIN_UNCONDITIONAL_FRAME = "LIN-UNCONDITIONAL-FRAME"
    USER_DEFINED_ETHERNET_FRAME = "USER-DEFINED-ETHERNET-FRAME"
