from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class FrameTriggeringSubtypesEnum(Enum):
    CAN_FRAME_TRIGGERING = "CAN-FRAME-TRIGGERING"
    ETHERNET_FRAME_TRIGGERING = "ETHERNET-FRAME-TRIGGERING"
    FLEXRAY_FRAME_TRIGGERING = "FLEXRAY-FRAME-TRIGGERING"
    FRAME_TRIGGERING = "FRAME-TRIGGERING"
    LIN_FRAME_TRIGGERING = "LIN-FRAME-TRIGGERING"
