from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class GlobalTimeMasterSubtypesEnum(Enum):
    GLOBAL_TIME_CAN_MASTER = "GLOBAL-TIME-CAN-MASTER"
    GLOBAL_TIME_ETH_MASTER = "GLOBAL-TIME-ETH-MASTER"
    GLOBAL_TIME_FR_MASTER = "GLOBAL-TIME-FR-MASTER"
    GLOBAL_TIME_MASTER = "GLOBAL-TIME-MASTER"
    USER_DEFINED_GLOBAL_TIME_MASTER = "USER-DEFINED-GLOBAL-TIME-MASTER"
