from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class GrantSubtypesEnum(Enum):
    COM_EVENT_GRANT = "COM-EVENT-GRANT"
    COM_FIELD_GRANT = "COM-FIELD-GRANT"
    COM_FIND_SERVICE_GRANT = "COM-FIND-SERVICE-GRANT"
    COM_GRANT = "COM-GRANT"
    COM_METHOD_GRANT = "COM-METHOD-GRANT"
    COM_OFFER_SERVICE_GRANT = "COM-OFFER-SERVICE-GRANT"
    ETHERNET_RAW_DATA_STREAM_GRANT = "ETHERNET-RAW-DATA-STREAM-GRANT"
    GRANT = "GRANT"
    RAW_DATA_STREAM_GRANT = "RAW-DATA-STREAM-GRANT"
