from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class LEnumSimple(Enum):
    """
    :cvar AA: Afar
    :cvar AB: Abkhazian
    :cvar AF: Afrikaans
    :cvar AM: Amharic
    :cvar AR: Arabic
    :cvar AS: Assamese
    :cvar AY: Aymara
    :cvar AZ: Azerbaijani
    :cvar BA: Bashkir
    :cvar BE: Byelorussian
    :cvar BG: Bulgarian
    :cvar BH: Bihari
    :cvar BI: Bislama
    :cvar BN: Bengali
    :cvar BO: Tibetian
    :cvar BR: Breton
    :cvar CA: Catalan
    :cvar CO: Corsican
    :cvar CS: Czech
    :cvar CY: Welsh
    :cvar DA: Danish
    :cvar DE: German
    :cvar DZ: Bhutani
    :cvar EL: Greek
    :cvar EN: English
    :cvar EO: Esperanto
    :cvar ES: Spanish
    :cvar ET: Estonian
    :cvar EU: Basque
    :cvar FA: Persian
    :cvar FI: Finnish
    :cvar FJ: Fiji
    :cvar FO: Faeroese
    :cvar FOR_ALL: The content applies to all languages
    :cvar FR: French
    :cvar FY: Frisian
    :cvar GA: Irish
    :cvar GD: Scots Gaelic
    :cvar GL: Galician
    :cvar GN: Guarani
    :cvar GU: Gjarati
    :cvar HA: Hausa
    :cvar HI: Hindi
    :cvar HR: Croatian
    :cvar HU: Hungarian
    :cvar HY: Armenian
    :cvar IA: Interlingua
    :cvar IE: Interlingue
    :cvar IK: Inupiak
    :cvar IN: Indonesian
    :cvar IS: Icelandic
    :cvar IT: Italian
    :cvar IW: Hebrew
    :cvar JA: Japanese
    :cvar JI: Yiddish
    :cvar JW: Javanese
    :cvar KA: Georgian
    :cvar KK: Kazakh
    :cvar KL: Greenlandic
    :cvar KM: Cambodian
    :cvar KN: Kannada
    :cvar KO: Korean
    :cvar KS: Kashmiri
    :cvar KU: Kurdish
    :cvar KY: Kirghiz
    :cvar LA: Latin
    :cvar LN: Lingala
    :cvar LO: Laothian
    :cvar LT: Lithuanian
    :cvar LV: Lavian, Lettish
    :cvar MG: Malagasy
    :cvar MI: Maori
    :cvar MK: Macedonian
    :cvar ML: Malayalam
    :cvar MN: Mongolian
    :cvar MO: Moldavian
    :cvar MR: Marathi
    :cvar MS: Malay
    :cvar MT: Maltese
    :cvar MY: Burmese
    :cvar NA: Nauru
    :cvar NE: Nepali
    :cvar NL: Dutch
    :cvar NO: Norwegian
    :cvar OC: Occitan
    :cvar OM: (Afan) Oromo
    :cvar OR: Oriya
    :cvar PA: Punjabi
    :cvar PL: Polish
    :cvar PS: Pashto, Pushto
    :cvar PT: Portuguese
    :cvar QU: Quechua
    :cvar RM: Rhaeto-Romance
    :cvar RN: Kirundi
    :cvar RO: Romanian
    :cvar RU: Russian
    :cvar RW: Kinyarwanda
    :cvar SA: Sanskrit
    :cvar SD: Sindhi
    :cvar SG: Sangro
    :cvar SH: Serbo-Croatian
    :cvar SI: Singhalese
    :cvar SK: Slovak
    :cvar SL: Slovenian
    :cvar SM: Samoan
    :cvar SN: Shona
    :cvar SO: Somali
    :cvar SQ: Albanian
    :cvar SR: Serbian
    :cvar SS: Siswati
    :cvar ST: Sesotho
    :cvar SU: Sundanese
    :cvar SV: Swedish
    :cvar SW: Swahili
    :cvar TA: Tamil
    :cvar TE: Tegulu
    :cvar TG: Tajik
    :cvar TH: Thai
    :cvar TI: Tigrinya
    :cvar TK: Turkmen
    :cvar TL: Tagalog
    :cvar TN: Setswana
    :cvar TO: Tonga
    :cvar TR: Turkish
    :cvar TS: Tsonga
    :cvar TT: Tatar
    :cvar TW: Twi
    :cvar UK: Ukrainian
    :cvar UR: Urdu
    :cvar UZ: Uzbek
    :cvar VI: Vietnamese
    :cvar VO: Volapuk
    :cvar WO: Wolof
    :cvar XH: Xhosa
    :cvar YO: Yoruba
    :cvar ZH: Chinese
    :cvar ZU: Zulu
    """

    AA = "AA"
    AB = "AB"
    AF = "AF"
    AM = "AM"
    AR = "AR"
    AS = "AS"
    AY = "AY"
    AZ = "AZ"
    BA = "BA"
    BE = "BE"
    BG = "BG"
    BH = "BH"
    BI = "BI"
    BN = "BN"
    BO = "BO"
    BR = "BR"
    CA = "CA"
    CO = "CO"
    CS = "CS"
    CY = "CY"
    DA = "DA"
    DE = "DE"
    DZ = "DZ"
    EL = "EL"
    EN = "EN"
    EO = "EO"
    ES = "ES"
    ET = "ET"
    EU = "EU"
    FA = "FA"
    FI = "FI"
    FJ = "FJ"
    FO = "FO"
    FOR_ALL = "FOR-ALL"
    FR = "FR"
    FY = "FY"
    GA = "GA"
    GD = "GD"
    GL = "GL"
    GN = "GN"
    GU = "GU"
    HA = "HA"
    HI = "HI"
    HR = "HR"
    HU = "HU"
    HY = "HY"
    IA = "IA"
    IE = "IE"
    IK = "IK"
    IN = "IN"
    IS = "IS"
    IT = "IT"
    IW = "IW"
    JA = "JA"
    JI = "JI"
    JW = "JW"
    KA = "KA"
    KK = "KK"
    KL = "KL"
    KM = "KM"
    KN = "KN"
    KO = "KO"
    KS = "KS"
    KU = "KU"
    KY = "KY"
    LA = "LA"
    LN = "LN"
    LO = "LO"
    LT = "LT"
    LV = "LV"
    MG = "MG"
    MI = "MI"
    MK = "MK"
    ML = "ML"
    MN = "MN"
    MO = "MO"
    MR = "MR"
    MS = "MS"
    MT = "MT"
    MY = "MY"
    NA = "NA"
    NE = "NE"
    NL = "NL"
    NO = "NO"
    OC = "OC"
    OM = "OM"
    OR = "OR"
    PA = "PA"
    PL = "PL"
    PS = "PS"
    PT = "PT"
    QU = "QU"
    RM = "RM"
    RN = "RN"
    RO = "RO"
    RU = "RU"
    RW = "RW"
    SA = "SA"
    SD = "SD"
    SG = "SG"
    SH = "SH"
    SI = "SI"
    SK = "SK"
    SL = "SL"
    SM = "SM"
    SN = "SN"
    SO = "SO"
    SQ = "SQ"
    SR = "SR"
    SS = "SS"
    ST = "ST"
    SU = "SU"
    SV = "SV"
    SW = "SW"
    TA = "TA"
    TE = "TE"
    TG = "TG"
    TH = "TH"
    TI = "TI"
    TK = "TK"
    TL = "TL"
    TN = "TN"
    TO = "TO"
    TR = "TR"
    TS = "TS"
    TT = "TT"
    TW = "TW"
    UK = "UK"
    UR = "UR"
    UZ = "UZ"
    VI = "VI"
    VO = "VO"
    WO = "WO"
    XH = "XH"
    YO = "YO"
    ZH = "ZH"
    ZU = "ZU"
