from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class PhysicalChannelSubtypesEnum(Enum):
    ABSTRACT_CAN_PHYSICAL_CHANNEL = "ABSTRACT-CAN-PHYSICAL-CHANNEL"
    CAN_PHYSICAL_CHANNEL = "CAN-PHYSICAL-CHANNEL"
    ETHERNET_PHYSICAL_CHANNEL = "ETHERNET-PHYSICAL-CHANNEL"
    FLEXRAY_PHYSICAL_CHANNEL = "FLEXRAY-PHYSICAL-CHANNEL"
    LIN_PHYSICAL_CHANNEL = "LIN-PHYSICAL-CHANNEL"
    PHYSICAL_CHANNEL = "PHYSICAL-CHANNEL"
    TTCAN_PHYSICAL_CHANNEL = "TTCAN-PHYSICAL-CHANNEL"
    USER_DEFINED_PHYSICAL_CHANNEL = "USER-DEFINED-PHYSICAL-CHANNEL"
