from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class PortInterfaceMappingSubtypesEnum(Enum):
    CLIENT_SERVER_INTERFACE_MAPPING = "CLIENT-SERVER-INTERFACE-MAPPING"
    MODE_INTERFACE_MAPPING = "MODE-INTERFACE-MAPPING"
    PORT_INTERFACE_MAPPING = "PORT-INTERFACE-MAPPING"
    TRIGGER_INTERFACE_MAPPING = "TRIGGER-INTERFACE-MAPPING"
    VARIABLE_AND_PARAMETER_INTERFACE_MAPPING = "VARIABLE-AND-PARAMETER-INTERFACE-MAPPING"
