from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class ProvidedApServiceInstanceSubtypesEnum(Enum):
    DDS_PROVIDED_SERVICE_INSTANCE = "DDS-PROVIDED-SERVICE-INSTANCE"
    PROVIDED_AP_SERVICE_INSTANCE = "PROVIDED-AP-SERVICE-INSTANCE"
    PROVIDED_SOMEIP_SERVICE_INSTANCE = "PROVIDED-SOMEIP-SERVICE-INSTANCE"
    PROVIDED_USER_DEFINED_SERVICE_INSTANCE = (
        "PROVIDED-USER-DEFINED-SERVICE-INSTANCE"
    )
