from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class RequiredApServiceInstanceSubtypesEnum(Enum):
    DDS_REQUIRED_SERVICE_INSTANCE = "DDS-REQUIRED-SERVICE-INSTANCE"
    REQUIRED_AP_SERVICE_INSTANCE = "REQUIRED-AP-SERVICE-INSTANCE"
    REQUIRED_SOMEIP_SERVICE_INSTANCE = "REQUIRED-SOMEIP-SERVICE-INSTANCE"
    REQUIRED_USER_DEFINED_SERVICE_INSTANCE = (
        "REQUIRED-USER-DEFINED-SERVICE-INSTANCE"
    )
