from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class RteEventSubtypesEnum(Enum):
    ASYNCHRONOUS_SERVER_CALL_RETURNS_EVENT = (
        "ASYNCHRONOUS-SERVER-CALL-RETURNS-EVENT"
    )
    BACKGROUND_EVENT = "BACKGROUND-EVENT"
    DATA_RECEIVE_ERROR_EVENT = "DATA-RECEIVE-ERROR-EVENT"
    DATA_RECEIVED_EVENT = "DATA-RECEIVED-EVENT"
    DATA_SEND_COMPLETED_EVENT = "DATA-SEND-COMPLETED-EVENT"
    DATA_WRITE_COMPLETED_EVENT = "DATA-WRITE-COMPLETED-EVENT"
    EXTERNAL_TRIGGER_OCCURRED_EVENT = "EXTERNAL-TRIGGER-OCCURRED-EVENT"
    INIT_EVENT = "INIT-EVENT"
    INTERNAL_TRIGGER_OCCURRED_EVENT = "INTERNAL-TRIGGER-OCCURRED-EVENT"
    MODE_SWITCHED_ACK_EVENT = "MODE-SWITCHED-ACK-EVENT"
    OPERATION_INVOKED_EVENT = "OPERATION-INVOKED-EVENT"
    OS_TASK_EXECUTION_EVENT = "OS-TASK-EXECUTION-EVENT"
    RTE_EVENT = "RTE-EVENT"
    SWC_MODE_MANAGER_ERROR_EVENT = "SWC-MODE-MANAGER-ERROR-EVENT"
    SWC_MODE_SWITCH_EVENT = "SWC-MODE-SWITCH-EVENT"
    TIMING_EVENT = "TIMING-EVENT"
    TRANSFORMER_HARD_ERROR_EVENT = "TRANSFORMER-HARD-ERROR-EVENT"
