from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class ServiceEventDeploymentSubtypesEnum(Enum):
    DDS_EVENT_DEPLOYMENT = "DDS-EVENT-DEPLOYMENT"
    SERVICE_EVENT_DEPLOYMENT = "SERVICE-EVENT-DEPLOYMENT"
    SOMEIP_EVENT_DEPLOYMENT = "SOMEIP-EVENT-DEPLOYMENT"
    USER_DEFINED_EVENT_DEPLOYMENT = "USER-DEFINED-EVENT-DEPLOYMENT"
