from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class ServiceInterfaceDeploymentSubtypesEnum(Enum):
    DDS_SERVICE_INTERFACE_DEPLOYMENT = "DDS-SERVICE-INTERFACE-DEPLOYMENT"
    SERVICE_INTERFACE_DEPLOYMENT = "SERVICE-INTERFACE-DEPLOYMENT"
    SOMEIP_SERVICE_INTERFACE_DEPLOYMENT = "SOMEIP-SERVICE-INTERFACE-DEPLOYMENT"
    USER_DEFINED_SERVICE_INTERFACE_DEPLOYMENT = "USER-DEFINED-SERVICE-INTERFACE-DEPLOYMENT"
