from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class ServiceNeedsSubtypesEnum(Enum):
    BSW_MGR_NEEDS = "BSW-MGR-NEEDS"
    COM_MGR_USER_NEEDS = "COM-MGR-USER-NEEDS"
    CRYPTO_CERTIFICATE_KEY_SLOT_NEEDS = "CRYPTO-CERTIFICATE-KEY-SLOT-NEEDS"
    CRYPTO_KEY_MANAGEMENT_NEEDS = "CRYPTO-KEY-MANAGEMENT-NEEDS"
    CRYPTO_NEEDS = "CRYPTO-NEEDS"
    CRYPTO_SERVICE_JOB_NEEDS = "CRYPTO-SERVICE-JOB-NEEDS"
    CRYPTO_SERVICE_NEEDS = "CRYPTO-SERVICE-NEEDS"
    DIAGNOSTIC_CAPABILITY_ELEMENT = "DIAGNOSTIC-CAPABILITY-ELEMENT"
    DIAGNOSTIC_CLEAR_CONDITION_NEEDS = "DIAGNOSTIC-CLEAR-CONDITION-NEEDS"
    DIAGNOSTIC_COMMUNICATION_MANAGER_NEEDS = (
        "DIAGNOSTIC-COMMUNICATION-MANAGER-NEEDS"
    )
    DIAGNOSTIC_COMPONENT_NEEDS = "DIAGNOSTIC-COMPONENT-NEEDS"
    DIAGNOSTIC_CONTROL_NEEDS = "DIAGNOSTIC-CONTROL-NEEDS"
    DIAGNOSTIC_ENABLE_CONDITION_NEEDS = "DIAGNOSTIC-ENABLE-CONDITION-NEEDS"
    DIAGNOSTIC_EVENT_INFO_NEEDS = "DIAGNOSTIC-EVENT-INFO-NEEDS"
    DIAGNOSTIC_EVENT_MANAGER_NEEDS = "DIAGNOSTIC-EVENT-MANAGER-NEEDS"
    DIAGNOSTIC_EVENT_NEEDS = "DIAGNOSTIC-EVENT-NEEDS"
    DIAGNOSTIC_GENERIC_UDS_NEEDS = "DIAGNOSTIC-GENERIC-UDS-NEEDS"
    DIAGNOSTIC_INDICATOR_NEEDS = "DIAGNOSTIC-INDICATOR-NEEDS"
    DIAGNOSTIC_IO_CONTROL_NEEDS = "DIAGNOSTIC-IO-CONTROL-NEEDS"
    DIAGNOSTIC_OPERATION_CYCLE_NEEDS = "DIAGNOSTIC-OPERATION-CYCLE-NEEDS"
    DIAGNOSTIC_REQUEST_FILE_TRANSFER_NEEDS = (
        "DIAGNOSTIC-REQUEST-FILE-TRANSFER-NEEDS"
    )
    DIAGNOSTIC_RESPONSE_ON_EVENT_NEEDS = "DIAGNOSTIC-RESPONSE-ON-EVENT-NEEDS"
    DIAGNOSTIC_ROUTINE_NEEDS = "DIAGNOSTIC-ROUTINE-NEEDS"
    DIAGNOSTIC_STORAGE_CONDITION_NEEDS = "DIAGNOSTIC-STORAGE-CONDITION-NEEDS"
    DIAGNOSTIC_UPLOAD_DOWNLOAD_NEEDS = "DIAGNOSTIC-UPLOAD-DOWNLOAD-NEEDS"
    DIAGNOSTIC_VALUE_NEEDS = "DIAGNOSTIC-VALUE-NEEDS"
    DIAGNOSTICS_COMMUNICATION_SECURITY_NEEDS = (
        "DIAGNOSTICS-COMMUNICATION-SECURITY-NEEDS"
    )
    DLT_USER_NEEDS = "DLT-USER-NEEDS"
    DO_IP_ACTIVATION_LINE_NEEDS = "DO-IP-ACTIVATION-LINE-NEEDS"
    DO_IP_GID_NEEDS = "DO-IP-GID-NEEDS"
    DO_IP_GID_SYNCHRONIZATION_NEEDS = "DO-IP-GID-SYNCHRONIZATION-NEEDS"
    DO_IP_POWER_MODE_STATUS_NEEDS = "DO-IP-POWER-MODE-STATUS-NEEDS"
    DO_IP_ROUTING_ACTIVATION_AUTHENTICATION_NEEDS = (
        "DO-IP-ROUTING-ACTIVATION-AUTHENTICATION-NEEDS"
    )
    DO_IP_ROUTING_ACTIVATION_CONFIRMATION_NEEDS = (
        "DO-IP-ROUTING-ACTIVATION-CONFIRMATION-NEEDS"
    )
    DO_IP_SERVICE_NEEDS = "DO-IP-SERVICE-NEEDS"
    DTC_STATUS_CHANGE_NOTIFICATION_NEEDS = (
        "DTC-STATUS-CHANGE-NOTIFICATION-NEEDS"
    )
    ECU_STATE_MGR_USER_NEEDS = "ECU-STATE-MGR-USER-NEEDS"
    ERROR_TRACER_NEEDS = "ERROR-TRACER-NEEDS"
    FUNCTION_INHIBITION_AVAILABILITY_NEEDS = (
        "FUNCTION-INHIBITION-AVAILABILITY-NEEDS"
    )
    FUNCTION_INHIBITION_NEEDS = "FUNCTION-INHIBITION-NEEDS"
    FURTHER_ACTION_BYTE_NEEDS = "FURTHER-ACTION-BYTE-NEEDS"
    GLOBAL_SUPERVISION_NEEDS = "GLOBAL-SUPERVISION-NEEDS"
    HARDWARE_TEST_NEEDS = "HARDWARE-TEST-NEEDS"
    IDS_MGR_CUSTOM_TIMESTAMP_NEEDS = "IDS-MGR-CUSTOM-TIMESTAMP-NEEDS"
    IDS_MGR_NEEDS = "IDS-MGR-NEEDS"
    INDICATOR_STATUS_NEEDS = "INDICATOR-STATUS-NEEDS"
    J_1939_DCM_DM_19_SUPPORT = "J-1939-DCM-DM-19-SUPPORT"
    J_1939_RM_INCOMING_REQUEST_SERVICE_NEEDS = (
        "J-1939-RM-INCOMING-REQUEST-SERVICE-NEEDS"
    )
    J_1939_RM_OUTGOING_REQUEST_SERVICE_NEEDS = (
        "J-1939-RM-OUTGOING-REQUEST-SERVICE-NEEDS"
    )
    NV_BLOCK_NEEDS = "NV-BLOCK-NEEDS"
    OBD_CONTROL_SERVICE_NEEDS = "OBD-CONTROL-SERVICE-NEEDS"
    OBD_INFO_SERVICE_NEEDS = "OBD-INFO-SERVICE-NEEDS"
    OBD_MONITOR_SERVICE_NEEDS = "OBD-MONITOR-SERVICE-NEEDS"
    OBD_PID_SERVICE_NEEDS = "OBD-PID-SERVICE-NEEDS"
    OBD_RATIO_DENOMINATOR_NEEDS = "OBD-RATIO-DENOMINATOR-NEEDS"
    OBD_RATIO_SERVICE_NEEDS = "OBD-RATIO-SERVICE-NEEDS"
    SECURE_ON_BOARD_COMMUNICATION_NEEDS = "SECURE-ON-BOARD-COMMUNICATION-NEEDS"
    SERVICE_NEEDS = "SERVICE-NEEDS"
    SUPERVISED_ENTITY_CHECKPOINT_NEEDS = "SUPERVISED-ENTITY-CHECKPOINT-NEEDS"
    SUPERVISED_ENTITY_NEEDS = "SUPERVISED-ENTITY-NEEDS"
    SYNC_TIME_BASE_MGR_USER_NEEDS = "SYNC-TIME-BASE-MGR-USER-NEEDS"
    V_2_X_FAC_USER_NEEDS = "V-2-X-FAC-USER-NEEDS"
    V_2_X_M_USER_NEEDS = "V-2-X-M-USER-NEEDS"
    VENDOR_SPECIFIC_SERVICE_NEEDS = "VENDOR-SPECIFIC-SERVICE-NEEDS"
    WARNING_INDICATOR_REQUESTED_BIT_NEEDS = (
        "WARNING-INDICATOR-REQUESTED-BIT-NEEDS"
    )
