from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class SwComponentTypeSubtypesEnum(Enum):
    ADAPTIVE_APPLICATION_SW_COMPONENT_TYPE = (
        "ADAPTIVE-APPLICATION-SW-COMPONENT-TYPE"
    )
    APPLICATION_SW_COMPONENT_TYPE = "APPLICATION-SW-COMPONENT-TYPE"
    ATOMIC_SW_COMPONENT_TYPE = "ATOMIC-SW-COMPONENT-TYPE"
    COMPLEX_DEVICE_DRIVER_SW_COMPONENT_TYPE = (
        "COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE"
    )
    COMPOSITION_SW_COMPONENT_TYPE = "COMPOSITION-SW-COMPONENT-TYPE"
    ECU_ABSTRACTION_SW_COMPONENT_TYPE = "ECU-ABSTRACTION-SW-COMPONENT-TYPE"
    NV_BLOCK_SW_COMPONENT_TYPE = "NV-BLOCK-SW-COMPONENT-TYPE"
    PARAMETER_SW_COMPONENT_TYPE = "PARAMETER-SW-COMPONENT-TYPE"
    SENSOR_ACTUATOR_SW_COMPONENT_TYPE = "SENSOR-ACTUATOR-SW-COMPONENT-TYPE"
    SERVICE_PROXY_SW_COMPONENT_TYPE = "SERVICE-PROXY-SW-COMPONENT-TYPE"
    SERVICE_SW_COMPONENT_TYPE = "SERVICE-SW-COMPONENT-TYPE"
    SW_COMPONENT_TYPE = "SW-COMPONENT-TYPE"
