from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class TdEventVfbSubtypesEnum(Enum):
    TD_EVENT_MODE_DECLARATION = "TD-EVENT-MODE-DECLARATION"
    TD_EVENT_OPERATION = "TD-EVENT-OPERATION"
    TD_EVENT_TRIGGER = "TD-EVENT-TRIGGER"
    TD_EVENT_VARIABLE_DATA_PROTOTYPE = "TD-EVENT-VARIABLE-DATA-PROTOTYPE"
    TD_EVENT_VFB = "TD-EVENT-VFB"
    TD_EVENT_VFB_PORT = "TD-EVENT-VFB-PORT"
    TD_EVENT_VFB_REFERENCE = "TD-EVENT-VFB-REFERENCE"
