from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class TimingDescriptionSubtypesEnum(Enum):
    TD_EVENT_BSW = "TD-EVENT-BSW"
    TD_EVENT_BSW_INTERNAL_BEHAVIOR = "TD-EVENT-BSW-INTERNAL-BEHAVIOR"
    TD_EVENT_BSW_MODE_DECLARATION = "TD-EVENT-BSW-MODE-DECLARATION"
    TD_EVENT_BSW_MODULE = "TD-EVENT-BSW-MODULE"
    TD_EVENT_COM = "TD-EVENT-COM"
    TD_EVENT_COMPLEX = "TD-EVENT-COMPLEX"
    TD_EVENT_CYCLE_START = "TD-EVENT-CYCLE-START"
    TD_EVENT_FR_CLUSTER_CYCLE_START = "TD-EVENT-FR-CLUSTER-CYCLE-START"
    TD_EVENT_FRAME = "TD-EVENT-FRAME"
    TD_EVENT_FRAME_ETHERNET = "TD-EVENT-FRAME-ETHERNET"
    TD_EVENT_I_PDU = "TD-EVENT-I-PDU"
    TD_EVENT_I_SIGNAL = "TD-EVENT-I-SIGNAL"
    TD_EVENT_MODE_DECLARATION = "TD-EVENT-MODE-DECLARATION"
    TD_EVENT_OPERATION = "TD-EVENT-OPERATION"
    TD_EVENT_SERVICE_INSTANCE = "TD-EVENT-SERVICE-INSTANCE"
    TD_EVENT_SERVICE_INSTANCE_DISCOVERY = "TD-EVENT-SERVICE-INSTANCE-DISCOVERY"
    TD_EVENT_SERVICE_INSTANCE_EVENT = "TD-EVENT-SERVICE-INSTANCE-EVENT"
    TD_EVENT_SERVICE_INSTANCE_FIELD = "TD-EVENT-SERVICE-INSTANCE-FIELD"
    TD_EVENT_SERVICE_INSTANCE_METHOD = "TD-EVENT-SERVICE-INSTANCE-METHOD"
    TD_EVENT_SWC = "TD-EVENT-SWC"
    TD_EVENT_SWC_INTERNAL_BEHAVIOR = "TD-EVENT-SWC-INTERNAL-BEHAVIOR"
    TD_EVENT_SWC_INTERNAL_BEHAVIOR_REFERENCE = (
        "TD-EVENT-SWC-INTERNAL-BEHAVIOR-REFERENCE"
    )
    TD_EVENT_TRIGGER = "TD-EVENT-TRIGGER"
    TD_EVENT_TT_CAN_CYCLE_START = "TD-EVENT-TT-CAN-CYCLE-START"
    TD_EVENT_VARIABLE_DATA_PROTOTYPE = "TD-EVENT-VARIABLE-DATA-PROTOTYPE"
    TD_EVENT_VFB = "TD-EVENT-VFB"
    TD_EVENT_VFB_PORT = "TD-EVENT-VFB-PORT"
    TD_EVENT_VFB_REFERENCE = "TD-EVENT-VFB-REFERENCE"
    TIMING_DESCRIPTION_EVENT = "TIMING-DESCRIPTION-EVENT"
    TIMING_DESCRIPTION_EVENT_CHAIN = "TIMING-DESCRIPTION-EVENT-CHAIN"
    TIMING_DESCRIPTION = "TIMING-DESCRIPTION"
