from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://autosar.org/schema/r4.0"


class TransformationPropsSubtypesEnum(Enum):
    AP_SOMEIP_TRANSFORMATION_PROPS = "AP-SOMEIP-TRANSFORMATION-PROPS"
    SOMEIP_TRANSFORMATION_PROPS = "SOMEIP-TRANSFORMATION-PROPS"
    TRANSFORMATION_PROPS = "TRANSFORMATION-PROPS"
    USER_DEFINED_TRANSFORMATION_PROPS = "USER-DEFINED-TRANSFORMATION-PROPS"
