exclude: "models|output"
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.3
    hooks:
      - id: docformatter
        args: ["--in-place", "--pre-summary-newline"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
        additional_dependencies: [tokenize-rt, types-requests, types-click]
