<?xml version="1.0" encoding="UTF-8"?>
<!--Created with WSDLGenerator 2.0.0 by Amadeus SAS-->
<!--  Amadeus Proprietary and Confidential Information: unauthorized use and disclosure strictly forbidden. 2015 - Amadeus s.a.s - All Rights Reserved.  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:amasec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:awsl="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:int="http://wsdl.amadeus.com/ServiceBookAndPrice_v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://wsdl.amadeus.com/ServiceBookAndPrice_v1_v4" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.amadeus.com/ServiceBookAndPrice_v1_v4" name="TSNIBE_ServiceBookAndPrice_1.2_4.0">
  <wsdl:documentation>Versions: [interface: 1.2 ; technical: 4.0]</wsdl:documentation>
  <wsp:Policy wsu:Id="MessagingPolicy">
    <wsam:Addressing wsp:Optional="true">
      <wsp:Policy>
        <wsam:AnonymousResponses />
      </wsp:Policy>
    </wsam:Addressing>
  </wsp:Policy>
  <wsp:Policy wsu:Id="AmadeusPolicy">
    <wsp:PolicyReference URI="#MessagingPolicy" />
  </wsp:Policy>
  <wsdl:import namespace="http://wsdl.amadeus.com/ServiceBookAndPrice_v1" location="ServiceBookAndPrice_1.2.wsdl" />
  <wsdl:types>
    <xs:schema>
      <xs:import schemaLocation="AMA/2012B/AMA_WS_Session.xsd" namespace="http://xml.amadeus.com/2010/06/Session_v3" />
      <xs:import schemaLocation="AMA_WSLink.xsd" namespace="http://wsdl.amadeus.com/2010/06/ws/Link_v1" />
      <xs:import schemaLocation="AMA/2012B/AMA_SecurityHostedUser.xsd" namespace="http://xml.amadeus.com/2010/06/Security_v1" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Session_3.000">
    <wsdl:part name="session" element="awsse:Session" />
  </wsdl:message>
  <wsdl:message name="TransactionFlowLink_1.0">
    <wsdl:part name="link" element="awsl:TransactionFlowLink" />
  </wsdl:message>
  <wsdl:message name="AMA_SecurityHostedUser_1.000">
    <wsdl:part name="security" element="amasec:AMA_SecurityHostedUser" />
  </wsdl:message>
  <wsdl:binding name="ServiceBookAndPrice_Binding" type="int:ServiceBookAndPrice_PT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Service_BookPriceProduct">
      <soap:operation soapAction="http://webservices.amadeus.com/Service_BookPriceProduct_1.1" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Service_BookPriceService">
      <soap:operation soapAction="http://webservices.amadeus.com/Service_BookPriceService_1.1" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServiceBookAndPrice_Service">
    <wsdl:port binding="tns:ServiceBookAndPrice_Binding" name="ServiceBookAndPrice_Port">
      <wsp:PolicyReference URI="#AmadeusPolicy" />
      <soap:address location="https://nodeD1.test.webservices.amadeus.com/1ASIWIBETSN" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
<!--1F8B08000000000000006D8D410B82401085EFFE8A3916A1CC8A15ED4D2B442810143A0F3AC292EECAB809FDFB96BA76793C78BCEF2BD9B29037CE8237132F9EA659438AEA142B15AB0334E45FD2D31BD451EF339D2194F77687A811A34773B941F9233881956509A0704F30C1E83C1AB61E689E47D37D151A5AA195C760110F5571854D886DE0E435589A5843C3B29A8E0BE79EB9ED6B093DAAAC6719A8FB3F834A3FD00E16F0C5000000-->
