from travelport.models.common_v48_0.common import Apiprovider
from travelport.models.common_v48_0.common import Arcpayment
from travelport.models.common_v48_0.common import AccountCode
from travelport.models.common_v48_0.common import AccountInformation
from travelport.models.common_v48_0.common import AccountingRemark
from travelport.models.common_v48_0.common import ActionStatus
from travelport.models.common_v48_0.common import AddSvc
from travelport.models.common_v48_0.common import AddressRestriction
from travelport.models.common_v48_0.common import AgencyContactInfo
from travelport.models.common_v48_0.common import AgencyInfo
from travelport.models.common_v48_0.common import AgencyInformation
from travelport.models.common_v48_0.common import AgencyPayment
from travelport.models.common_v48_0.common import AgencySellInfo
from travelport.models.common_v48_0.common import AgentAction
from travelport.models.common_v48_0.common import AgentIdoverride
from travelport.models.common_v48_0.common import AgentVoucher
from travelport.models.common_v48_0.common import AirExchangeInfo
from travelport.models.common_v48_0.common import AirSearchParameters
from travelport.models.common_v48_0.common import AirSeatAssignment
from travelport.models.common_v48_0.common import Airport
from travelport.models.common_v48_0.common import AppliedProfile
from travelport.models.common_v48_0.common import Auxdata
from travelport.models.common_v48_0.common import Bsppayment
from travelport.models.common_v48_0.common import BaseAsyncProviderSpecificResponse
from travelport.models.common_v48_0.common_req_rsp import BaseCoreReq
from travelport.models.common_v48_0.common_req_rsp import BaseCoreSearchReq
from travelport.models.common_v48_0.common_req_rsp import BaseCreateReservationReq
from travelport.models.common_v48_0.common_req_rsp import BaseCreateWithFormOfPaymentReq
from travelport.models.common_v48_0.common_req_rsp import BaseReq
from travelport.models.common_v48_0.common import BaseReservation
from travelport.models.common_v48_0.common_req_rsp import BaseRsp
from travelport.models.common_v48_0.common_req_rsp import BaseSearchReq
from travelport.models.common_v48_0.common_req_rsp import BaseSearchRsp
from travelport.models.common_v48_0.common import BillingPointOfSaleInfo
from travelport.models.common_v48_0.common import BookingDates
from travelport.models.common_v48_0.common import BookingSource
from travelport.models.common_v48_0.common import BookingTraveler
from travelport.models.common_v48_0.common import BookingTravelerInfo
from travelport.models.common_v48_0.common import BookingTravelerInformation
from travelport.models.common_v48_0.common import BookingTravelerName
from travelport.models.common_v48_0.common import BookingTravelerRef
from travelport.models.common_v48_0.common import CabinClass
from travelport.models.common_v48_0.common import CardRestriction
from travelport.models.common_v48_0.common import Carrier
from travelport.models.common_v48_0.common import Certificate
from travelport.models.common_v48_0.common import Characteristic
from travelport.models.common_v48_0.common import Check
from travelport.models.common_v48_0.common import City
from travelport.models.common_v48_0.common import CityOrAirport
from travelport.models.common_v48_0.common import Commission
from travelport.models.common_v48_0.common import CommissionRemark
from travelport.models.common_v48_0.common import ConnectionPoint
from travelport.models.common_v48_0.common import ConsolidatorRemark
from travelport.models.common_v48_0.common import ContinuityCheckOverride
from travelport.models.common_v48_0.common import CoordinateLocation
from travelport.models.common_v48_0.common import CorporateDiscountId
from travelport.models.common_v48_0.common import Credentials
from travelport.models.common_v48_0.common import CreditCard
from travelport.models.common_v48_0.common import CreditCardAuth
from travelport.models.common_v48_0.common import CustomProfileInformation
from travelport.models.common_v48_0.common import CustomerId
from travelport.models.common_v48_0.common import CustomizedNameData
from travelport.models.common_v48_0.common import DebitCard
from travelport.models.common_v48_0.common import DeliveryInfo
from travelport.models.common_v48_0.common import DirectPayment
from travelport.models.common_v48_0.common import DiscountCard
from travelport.models.common_v48_0.common import DiscountCardRef
from travelport.models.common_v48_0.common import Distance
from travelport.models.common_v48_0.common import DistanceUnits
from travelport.models.common_v48_0.common import DriversLicense
from travelport.models.common_v48_0.common import DriversLicenseRef
from travelport.models.common_v48_0.common import Email
from travelport.models.common_v48_0.common import EmailNotification
from travelport.models.common_v48_0.common import Endorsement
from travelport.models.common_v48_0.common import EnettVan
from travelport.models.common_v48_0.common_req_rsp import ErrorInfo
from travelport.models.common_v48_0.common import ExchangedCoupon
from travelport.models.common_v48_0.common import FileFinishingInfo
from travelport.models.common_v48_0.common import FormOfPayment
from travelport.models.common_v48_0.common import FormOfPaymentRef
from travelport.models.common_v48_0.common import FormattedTextTextType
from travelport.models.common_v48_0.common import GeneralRemark
from travelport.models.common_v48_0.common import Group
from travelport.models.common_v48_0.common import Guarantee
from travelport.models.common_v48_0.common import GuaranteeType
from travelport.models.common_v48_0.common import HostToken
from travelport.models.common_v48_0.common import HostTokenList
from travelport.models.common_v48_0.common import IncludedInBase
from travelport.models.common_v48_0.common import IndustryStandardSsr
from travelport.models.common_v48_0.common import InvoiceData
from travelport.models.common_v48_0.common import InvoiceRemark
from travelport.models.common_v48_0.common import KeyMapping
from travelport.models.common_v48_0.common import Keyword
from travelport.models.common_v48_0.common import LinkedUniversalRecord
from travelport.models.common_v48_0.common import Location
from travelport.models.common_v48_0.common import LocationAddress
from travelport.models.common_v48_0.common import LocatorCode
from travelport.models.common_v48_0.common import LoyaltyCard
from travelport.models.common_v48_0.common import LoyaltyCardRef
from travelport.models.common_v48_0.common import LoyaltyProgram
from travelport.models.common_v48_0.common import Mco
from travelport.models.common_v48_0.common import McoexchangeInfo
from travelport.models.common_v48_0.common import McofeeInfo
from travelport.models.common_v48_0.common import Mcoinformation
from travelport.models.common_v48_0.common import McopriceData
from travelport.models.common_v48_0.common import Mcoremark
from travelport.models.common_v48_0.common import Mcotext
from travelport.models.common_v48_0.common import MarketingInformation
from travelport.models.common_v48_0.common import MealRequest
from travelport.models.common_v48_0.common import MediaItem
from travelport.models.common_v48_0.common import MetaData
from travelport.models.common_v48_0.common import MiscFormOfPayment
from travelport.models.common_v48_0.common import ModificationType
from travelport.models.common_v48_0.common import Name
from travelport.models.common_v48_0.common import NameOverride
from travelport.models.common_v48_0.common import NameRemark
from travelport.models.common_v48_0.common import NextResultReference
from travelport.models.common_v48_0.common import Osi
from travelport.models.common_v48_0.common import OperatedBy
from travelport.models.common_v48_0.common import OptionalServiceApplicabilityType
from travelport.models.common_v48_0.common import OptionalServiceApplicationLimitType
from travelport.models.common_v48_0.common import OtherGuaranteeInfo
from travelport.models.common_v48_0.common import OverridePcc
from travelport.models.common_v48_0.common import OwnershipChange
from travelport.models.common_v48_0.common import PassengerInfo
from travelport.models.common_v48_0.common import PassiveInfo
from travelport.models.common_v48_0.common import Payment
from travelport.models.common_v48_0.common import PaymentAdvice
from travelport.models.common_v48_0.common import PaymentRef
from travelport.models.common_v48_0.common import PaymentRestriction
from travelport.models.common_v48_0.common import Penalty
from travelport.models.common_v48_0.common import PermittedProviders
from travelport.models.common_v48_0.common import PersonalGeography
from travelport.models.common_v48_0.common import PhoneNumber
from travelport.models.common_v48_0.common import PointOfCommencement
from travelport.models.common_v48_0.common import PointOfSale
from travelport.models.common_v48_0.common import PolicyInformation
from travelport.models.common_v48_0.common import Postscript
from travelport.models.common_v48_0.common import PriceMatchError
from travelport.models.common_v48_0.common import Provider
from travelport.models.common_v48_0.common import ProviderArnksegment
from travelport.models.common_v48_0.common import ProviderReservationDetail
from travelport.models.common_v48_0.common import ProviderReservationInfoRef
from travelport.models.common_v48_0.common import PseudoCityCode
from travelport.models.common_v48_0.common import QueuePlace
from travelport.models.common_v48_0.common import QueueSelector
from travelport.models.common_v48_0.common import RailLocation
from travelport.models.common_v48_0.common import RailSeatAssignment
from travelport.models.common_v48_0.common import ReferencePoint
from travelport.models.common_v48_0.common import RefundRemark
from travelport.models.common_v48_0.common import Remark
from travelport.models.common_v48_0.common import RequestKeyMappings
from travelport.models.common_v48_0.common import RequiredField
from travelport.models.common_v48_0.common import Requisition
from travelport.models.common_v48_0.common import ReservationName
from travelport.models.common_v48_0.common import ResponseMessage
from travelport.models.common_v48_0.common import Restriction
from travelport.models.common_v48_0.common import ReviewBooking
from travelport.models.common_v48_0.common import RoleInfo
from travelport.models.common_v48_0.common import Ssr
from travelport.models.common_v48_0.common import Ssrinfo
from travelport.models.common_v48_0.common import SearchEvent
from travelport.models.common_v48_0.common import SearchPassenger
from travelport.models.common_v48_0.common import SearchTicketing
from travelport.models.common_v48_0.common import SearchTicketingReservationStatus
from travelport.models.common_v48_0.common import SearchTicketingTicketStatus
from travelport.models.common_v48_0.common import SeatAssignment
from travelport.models.common_v48_0.common import SeatAttribute
from travelport.models.common_v48_0.common import SeatAttributes
from travelport.models.common_v48_0.common import Segment
from travelport.models.common_v48_0.common import SegmentRemark
from travelport.models.common_v48_0.common import SellMessage
from travelport.models.common_v48_0.common import ServiceData
from travelport.models.common_v48_0.common import ServiceFeeInfo
from travelport.models.common_v48_0.common import ServiceFeeTaxInfo
from travelport.models.common_v48_0.common import ServiceInfo
from travelport.models.common_v48_0.common import ServiceRuleType
from travelport.models.common_v48_0.common import ShopInformation
from travelport.models.common_v48_0.common import SimpleName
from travelport.models.common_v48_0.common import SpecialEquipment
from travelport.models.common_v48_0.common import State
from travelport.models.common_v48_0.common import StockControl
from travelport.models.common_v48_0.common import SupplierLocator
from travelport.models.common_v48_0.common import TaxDetail
from travelport.models.common_v48_0.common import TerminalSessionInfo
from travelport.models.common_v48_0.common import ThirdPartyInformation
from travelport.models.common_v48_0.common import TicketNumber
from travelport.models.common_v48_0.common import TransactionType
from travelport.models.common_v48_0.common import TravelComplianceData
from travelport.models.common_v48_0.common import TravelInfo
from travelport.models.common_v48_0.common import TravelSegment
from travelport.models.common_v48_0.common import TravelerInformation
from travelport.models.common_v48_0.common import TravelerType
from travelport.models.common_v48_0.common import UrticketStatus
from travelport.models.common_v48_0.common import UnassociatedRemark
from travelport.models.common_v48_0.common import UnitedNations
from travelport.models.common_v48_0.common import VendorLocation
from travelport.models.common_v48_0.common import Xmlremark
from travelport.models.common_v48_0.common import TypeAdjustmentTarget
from travelport.models.common_v48_0.common import TypeAdjustmentType
from travelport.models.common_v48_0.common import TypeAgencyHierarchyLongReference
from travelport.models.common_v48_0.common import TypeAgencyHierarchyReference
from travelport.models.common_v48_0.common import TypeAgencyPayment
from travelport.models.common_v48_0.common import TypeAgencyProfileLevel
from travelport.models.common_v48_0.common import TypeAgentInfo
from travelport.models.common_v48_0.common import TypeAssociatedRemark
from travelport.models.common_v48_0.common import TypeAssociatedRemarkWithSegmentRef
from travelport.models.common_v48_0.common import TypeBookingTransactionsAllowed
from travelport.models.common_v48_0.common import TypeCommissionLevel
from travelport.models.common_v48_0.common import TypeCommissionModifier
from travelport.models.common_v48_0.common import TypeCommissionType
from travelport.models.common_v48_0.common import TypeCreditCardType
from travelport.models.common_v48_0.common import TypeDateRange
from travelport.models.common_v48_0.common import TypeDirection
from travelport.models.common_v48_0.common import TypeDistance
from travelport.models.common_v48_0.common import TypeDoorCount
from travelport.models.common_v48_0.common import TypeElement
from travelport.models.common_v48_0.common import TypeElementStatus
from travelport.models.common_v48_0.common import TypeErrorInfo
from travelport.models.common_v48_0.common import TypeEventType
from travelport.models.common_v48_0.common import TypeFarePull
from travelport.models.common_v48_0.common import TypeFeeInfo
from travelport.models.common_v48_0.common import TypeFlexibleTimeSpec
from travelport.models.common_v48_0.common import TypeFormOfPaymentPnrreference
from travelport.models.common_v48_0.common import TypeFormOfRefund
from travelport.models.common_v48_0.common import TypeFreeFormText
from travelport.models.common_v48_0.common import TypeFuel
from travelport.models.common_v48_0.common import TypeFulfillmentIdtype
from travelport.models.common_v48_0.common import TypeFulfillmentType
from travelport.models.common_v48_0.common import TypeGeneralReference
from travelport.models.common_v48_0.common import TypeGuaranteeInformation
from travelport.models.common_v48_0.common import TypeImageSize
from travelport.models.common_v48_0.common import TypeInvoiceRecordCategory
from travelport.models.common_v48_0.common import TypeItineraryCode
from travelport.models.common_v48_0.common import TypeItineraryType
from travelport.models.common_v48_0.common import TypeKeyBasedReference
from travelport.models.common_v48_0.common import TypeKeyword
from travelport.models.common_v48_0.common import TypeLicenseCode
from travelport.models.common_v48_0.common import TypeLocation
from travelport.models.common_v48_0.common_req_rsp import TypeLoggingLevel
from travelport.models.common_v48_0.common import TypeMcofeeType
from travelport.models.common_v48_0.common import TypeMcostatus
from travelport.models.common_v48_0.common import TypeMcotype
from travelport.models.common_v48_0.common import TypeNonAirReservationRef
from travelport.models.common_v48_0.common import TypeOtakeyword
from travelport.models.common_v48_0.common import TypeOtasubKey
from travelport.models.common_v48_0.common import TypeOtherImageSize
from travelport.models.common_v48_0.common import TypePassengerType
from travelport.models.common_v48_0.common import TypePaymentCard
from travelport.models.common_v48_0.common import TypePolicy
from travelport.models.common_v48_0.common import TypePolicyCodesList
from travelport.models.common_v48_0.common import TypePriceClassOfService
from travelport.models.common_v48_0.common import TypePricingType
from travelport.models.common_v48_0.common import TypeProduct
from travelport.models.common_v48_0.common import TypeProfileApplicability
from travelport.models.common_v48_0.common import TypeProfileEntityStatus
from travelport.models.common_v48_0.common import TypeProfileEntityStatusWithDelete
from travelport.models.common_v48_0.common import TypeProfileLevel
from travelport.models.common_v48_0.common import TypeProfileLevelWithCredential
from travelport.models.common_v48_0.common import TypeProfileLevelWithSystem
from travelport.models.common_v48_0.common import TypeProfileRef
from travelport.models.common_v48_0.common import TypeProfileType
from travelport.models.common_v48_0.common import TypeProviderReservationDetail
from travelport.models.common_v48_0.common import TypeProviderReservationSpecificInfo
from travelport.models.common_v48_0.common import TypeProviderToken
from travelport.models.common_v48_0.common import TypePurchaseWindow
from travelport.models.common_v48_0.common import TypeQueueModifyAction
from travelport.models.common_v48_0.common import TypeRateCategory
from travelport.models.common_v48_0.common import TypeRateDescription
from travelport.models.common_v48_0.common import TypeRateGuarantee
from travelport.models.common_v48_0.common import TypeRateTimePeriod
from travelport.models.common_v48_0.common import TypeRecordStatus
from travelport.models.common_v48_0.common import TypeRemark
from travelport.models.common_v48_0.common import TypeRemarkWithTravelerRef
from travelport.models.common_v48_0.common import TypeReqSeat
from travelport.models.common_v48_0.common import TypeReserveRequirement
from travelport.models.common_v48_0.common import TypeResidency
from travelport.models.common_v48_0.common import TypeResponseImageSize
from travelport.models.common_v48_0.common import TypeResultMessage
from travelport.models.common_v48_0.common import TypeSearchLocation
from travelport.models.common_v48_0.common import TypeSearchTimeSpec
from travelport.models.common_v48_0.common import TypeSegmentRef
from travelport.models.common_v48_0.common import TypeSource
from travelport.models.common_v48_0.common import TypeSpecificTime
from travelport.models.common_v48_0.common import TypeStatus
from travelport.models.common_v48_0.common import TypeStructuredAddress
from travelport.models.common_v48_0.common import TypeSubKey
from travelport.models.common_v48_0.common import TypeTax
from travelport.models.common_v48_0.common import TypeTaxInfo
from travelport.models.common_v48_0.common import TypeTicketStatus
from travelport.models.common_v48_0.common import TypeTimeRange
from travelport.models.common_v48_0.common import TypeTimeSpec
from travelport.models.common_v48_0.common import TypeTransactionsAllowed
from travelport.models.common_v48_0.common import TypeTrinary
from travelport.models.common_v48_0.common import TypeVehicleCategory
from travelport.models.common_v48_0.common import TypeVehicleClass
from travelport.models.common_v48_0.common import TypeVehicleLocation
from travelport.models.common_v48_0.common import TypeVehicleTransmission
from travelport.models.common_v48_0.common import TypeVendorLocation
from travelport.models.common_v48_0.common import TypeVoucherInformation
from travelport.models.common_v48_0.common import TypeVoucherType
