from enum import Enum

__NAMESPACE__ = "http://www.netex.org.uk/netex"


class ParkingVehicleEnumeration(Enum):
    PEDAL_CYCLE = "pedalCycle"
    MOPED = "moped"
    MOTORCYCLE = "motorcycle"
    MOTORCYCLE_WITH_SIDECAR = "motorcycleWithSidecar"
    MOTOR_SCOOTER = "motorScooter"
    TWO_WHEELED_VEHICLE = "twoWheeledVehicle"
    THREE_WHEELED_VEHICLE = "threeWheeledVehicle"
    CAR = "car"
    SMALL_CAR = "smallCar"
    PASSENGER_CAR = "passengerCar"
    LARGE_CAR = "largeCar"
    FOUR_WHEEL_DRIVE = "fourWheelDrive"
    TAXI = "taxi"
    CAMPER_CAR = "camperCar"
    CAR_WITH_TRAILER = "carWithTrailer"
    CAR_WITH_CARAVAN = "carWithCaravan"
    MINIBUS = "minibus"
    BUS = "bus"
    VAN = "van"
    LARGE_VAN = "largeVan"
    HIGH_SIDED_VEHICLE = "highSidedVehicle"
    LIGHT_GOODS_VEHICLE = "lightGoodsVehicle"
    HEAVY_GOODS_VEHICLE = "heavyGoodsVehicle"
    AGRICULTURAL_VEHICLE = "agriculturalVehicle"
    TANKER = "tanker"
    TRUCK = "truck"
    TRAM = "tram"
    ARTICULATED_VEHICLE = "articulatedVehicle"
    VEHICLE_WITH_TRAILER = "vehicleWithTrailer"
    LIGHT_GOODS_VEHICLE_WITH_TRAILER = "lightGoodsVehicleWithTrailer"
    HEAVY_GOODS_VEHICLE_WITH_TRAILER = "heavyGoodsVehicleWithTrailer"
    UNDEFINED = "undefined"
    OTHER = "other"
    ALL_PASSENGER_VEHICLES = "allPassengerVehicles"
    ALL = "all"
