from enum import Enum

__NAMESPACE__ = "http://www.netex.org.uk/netex"


class QuayTypeEnumeration(Enum):
    AIRLINE_GATE = "airlineGate"
    RAIL_PLATFORM = "railPlatform"
    RAIL_ISLAND_PLATFORM = "railIslandPlatform"
    RAIL_PLATFORM_SECTOR = "railPlatformSector"
    METRO_PLATFORM = "metroPlatform"
    METRO_ISLAND_PLATFORM = "metroIslandPlatform"
    METRO_ISLAND_PLATFORM_SECTOR = "metroIslandPlatformSector"
    COACH_STOP = "coachStop"
    BUS_STOP = "busStop"
    BUS_PLATFORM = "busPlatform"
    BUS_BAY = "busBay"
    TRAM_PLATFORM = "tramPlatform"
    TRAM_STOP = "tramStop"
    BOAT_QUAY = "boatQuay"
    FERRY_LANDING = "ferryLanding"
    TELECABIN_PLATFORM = "telecabinPlatform"
    TAXI_STAND = "taxiStand"
    SET_DOWN_PLACE = "setDownPlace"
    VEHICLE_LOADING_PLACE = "vehicleLoadingPlace"
    HANDICAPPED_LEVEL_BOARDING_SECTOR = "handicappedLevelBoardingSector"
    MULTIMODAL = "multimodal"
    BUS_STOP_WITHIN_ROADWAY_BOARDING = "busStopWithinRoadwayBoarding"
    TRAM_STOP_WITHIN_ROADWAY_BOARDING = "tramStopWithinRoadwayBoarding"
    OTHER = "other"
