from __future__ import annotations

from dataclasses import dataclass, field

__NAMESPACE__ = "http://www.travelport.com/schema/common_v37_0"


@dataclass
class BillingPointOfSaleInfo5:
    """
    Point of Sale information for Billing.

    Parameters
    ----------
    origin_application
        Name of the Point of Sale application which initiated the
        Request.This information will be provided as part of the
        provisioning of the user.
    cidbnumber
        A 10 Digit customer number generated by CIDB system.
    """

    class Meta:
        name = "BillingPointOfSaleInfo"
        namespace = "http://www.travelport.com/schema/common_v37_0"

    origin_application: None | str = field(
        default=None,
        metadata={
            "name": "OriginApplication",
            "type": "Attribute",
            "required": True,
        },
    )
    cidbnumber: None | str = field(
        default=None,
        metadata={
            "name": "CIDBNumber",
            "type": "Attribute",
            "pattern": r"\d{10}",
        },
    )
