from __future__ import annotations
from enum import Enum

__NAMESPACE__ = "http://www.travelport.com/schema/common_v52_0"


class TypeVehicleClass(Enum):
    """
    The class of vehicle.
    """
    MINI = "Mini"
    ECONOMY = "Economy"
    COMPACT = "Compact"
    INTERMEDIATE = "Intermediate"
    STANDARD = "Standard"
    FULLSIZE = "Fullsize"
    LUXURY = "Luxury"
    PREMIUM = "Premium"
    SPECIAL = "Special"
    MINI_ELITE = "MiniElite"
    ECONOMY_ELITE = "EconomyElite"
    COMPACT_ELITE = "CompactElite"
    INTERMEDIATE_ELITE = "IntermediateElite"
    STANDARD_ELITE = "StandardElite"
    FULLSIZE_ELITE = "FullsizeElite"
    PREMIUM_ELITE = "PremiumElite"
    LUXURY_ELITE = "LuxuryElite"
    OVERSIZE = "Oversize"
    SUBCOMPACT = "Subcompact"
    MINIVAN = "Minivan"
    TWELVE_PASSENGER_VAN = "TwelvePassengerVan"
    MOVING_VAN = "MovingVan"
    FIFTEEN_PASSENGER_VAN = "FifteenPassengerVan"
    CARGO_VAN = "CargoVan"
    TWELVE_FOOT_TRUCK = "TwelveFootTruck"
    TWENTY_FOOT_TRUCK = "TwentyFootTruck"
    TWENTYFOUR_FOOT_TRUCK = "TwentyfourFootTruck"
    TWENTYSIX_FOOT_TRUCK = "TwentysixFootTruck"
    MOPED = "Moped"
    STRETCH = "Stretch"
    REGULAR = "Regular"
    UNIQUE = "Unique"
    EXOTIC = "Exotic"
    SMALL_OR_MEDIUM_TRUCK = "SmallOrMediumTruck"
    LARGE_TRUCK = "LargeTruck"
    SMALL_SUV = "SmallSUV"
    MEDIUM_SUV = "MediumSUV"
    LARGE_SUV = "LargeSUV"
    EXOTIC_SUV = "ExoticSUV"
    FOUR_WHEEL_DRIVE = "FourWheelDrive"
