from dataclasses import dataclass, field
from typing import Optional

from xsdata.models.datatype import XmlDateTime

from datexii.models.eu.datexii.v2.extension_type import ExtensionType
from datexii.models.eu.datexii.v2.fault_severity_enum import FaultSeverityEnum

__NAMESPACE__ = "http://datex2.eu/schema/2/2_0"


@dataclass
class Fault:
    """
    Information about a fault relating to a specific piece of equipment or process.

    :ivar fault_identifier: Unique identifier of the fault.
    :ivar fault_description: Textual description of the fault.
    :ivar fault_creation_time: The date and time at which the fault was
        originally recorded/reported.
    :ivar fault_last_update_time: The date and time at which the fault
        information as specified in this instance was last updated.
    :ivar fault_severity: The severity of the fault in terms of how it
        affects the usability of the equipment or the reliability of the
        data generated by the equipment.
    :ivar fault_extension:
    """

    fault_identifier: Optional[str] = field(
        default=None,
        metadata={
            "name": "faultIdentifier",
            "type": "Element",
            "namespace": "http://datex2.eu/schema/2/2_0",
            "max_length": 1024,
        },
    )
    fault_description: Optional[str] = field(
        default=None,
        metadata={
            "name": "faultDescription",
            "type": "Element",
            "namespace": "http://datex2.eu/schema/2/2_0",
            "max_length": 1024,
        },
    )
    fault_creation_time: Optional[XmlDateTime] = field(
        default=None,
        metadata={
            "name": "faultCreationTime",
            "type": "Element",
            "namespace": "http://datex2.eu/schema/2/2_0",
        },
    )
    fault_last_update_time: Optional[XmlDateTime] = field(
        default=None,
        metadata={
            "name": "faultLastUpdateTime",
            "type": "Element",
            "namespace": "http://datex2.eu/schema/2/2_0",
            "required": True,
        },
    )
    fault_severity: Optional[FaultSeverityEnum] = field(
        default=None,
        metadata={
            "name": "faultSeverity",
            "type": "Element",
            "namespace": "http://datex2.eu/schema/2/2_0",
        },
    )
    fault_extension: Optional[ExtensionType] = field(
        default=None,
        metadata={
            "name": "faultExtension",
            "type": "Element",
            "namespace": "http://datex2.eu/schema/2/2_0",
        },
    )
