from enum import Enum

__NAMESPACE__ = "http://datex2.eu/schema/2/2_0"


class FaultSeverityEnum(Enum):
    """
    Classification of the severity of faults.

    :cvar LOW: The fault is of low severity and has only limited impact
        on the usability of the equipment or the value of the data
        generated by the equipment.
    :cvar MEDIUM: The fault is of medium severity which will
        significantly limit the usability of the equipment or devalue
        the usefulness of the data generated by the equipment.
    :cvar HIGH: The fault is of high severity which will render the
        equipment unusable or any data generated by the equipment to be
        of no value.
    :cvar UNKNOWN: The fault is of unknown severity and hence its effect
        on the usability of the equipment or the usefulness of the data
        generated by the equipment can not be assessed.
    """
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    UNKNOWN = "unknown"
