from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "urn:vpro:shared:2009"


class LicenseEnum(Enum):
    COPYRIGHTED = "COPYRIGHTED"
    PUBLIC_DOMAIN = "PUBLIC_DOMAIN"
    CC_BY = "CC_BY"
    CC_BY_1_0 = "CC_BY_1_0"
    CC_BY_2_0 = "CC_BY_2_0"
    CC_BY_3_0 = "CC_BY_3_0"
    CC_BY_4_0 = "CC_BY_4_0"
    CC_BY_SA = "CC_BY_SA"
    CC_BY_SA_1_0 = "CC_BY_SA_1_0"
    CC_BY_SA_2_0 = "CC_BY_SA_2_0"
    CC_BY_SA_3_0 = "CC_BY_SA_3_0"
    CC_BY_SA_4_0 = "CC_BY_SA_4_0"
    CC_BY_ND = "CC_BY_ND"
    CC_BY_ND_1_0 = "CC_BY_ND_1_0"
    CC_BY_ND_2_0 = "CC_BY_ND_2_0"
    CC_BY_ND_3_0 = "CC_BY_ND_3_0"
    CC_BY_ND_4_0 = "CC_BY_ND_4_0"
    CC_BY_NC = "CC_BY_NC"
    CC_BY_NC_1_0 = "CC_BY_NC_1_0"
    CC_BY_NC_2_0 = "CC_BY_NC_2_0"
    CC_BY_NC_3_0 = "CC_BY_NC_3_0"
    CC_BY_NC_4_0 = "CC_BY_NC_4_0"
    CC_BY_NC_SA = "CC_BY_NC_SA"
    CC_BY_NC_SA_1_0 = "CC_BY_NC_SA_1_0"
    CC_BY_NC_SA_2_0 = "CC_BY_NC_SA_2_0"
    CC_BY_NC_SA_3_0 = "CC_BY_NC_SA_3_0"
    CC_BY_NC_SA_4_0 = "CC_BY_NC_SA_4_0"
    CC_BY_NC_ND = "CC_BY_NC_ND"
    CC_BY_NC_ND_1_0 = "CC_BY_NC_ND_1_0"
    CC_BY_NC_ND_2_0 = "CC_BY_NC_ND_2_0"
    CC_BY_NC_ND_3_0 = "CC_BY_NC_ND_3_0"
    CC_BY_NC_ND_4_0 = "CC_BY_NC_ND_4_0"
    USA_GOV = "USA_GOV"
