from enum import Enum

__NAMESPACE__ = "http://www.accellera.org/XMLSchema/IPXACT/1685-2022"


class SimpleFileType(Enum):
    UNKNOWN = "unknown"
    C_SOURCE = "cSource"
    CPP_SOURCE = "cppSource"
    ASM_SOURCE = "asmSource"
    VHDL_SOURCE = "vhdlSource"
    VHDL_SOURCE_87 = "vhdlSource-87"
    VHDL_SOURCE_93 = "vhdlSource-93"
    VHDL_SOURCE_2002 = "vhdlSource-2002"
    VHDL_SOURCE_2008 = "vhdlSource-2008"
    VERILOG_SOURCE = "verilogSource"
    VERILOG_SOURCE_95 = "verilogSource-95"
    VERILOG_SOURCE_2001 = "verilogSource-2001"
    VERILOG_SOURCE_2005 = "verilogSource-2005"
    SW_OBJECT = "swObject"
    SW_OBJECT_LIBRARY = "swObjectLibrary"
    VHDL_BINARY_LIBRARY = "vhdlBinaryLibrary"
    VERILOG_BINARY_LIBRARY = "verilogBinaryLibrary"
    UNELABORATED_HDL = "unelaboratedHdl"
    EXECUTABLE_HDL = "executableHdl"
    SYSTEM_VERILOG_SOURCE = "systemVerilogSource"
    SYSTEM_VERILOG_SOURCE_3_0 = "systemVerilogSource-3.0"
    SYSTEM_VERILOG_SOURCE_3_1 = "systemVerilogSource-3.1"
    SYSTEM_VERILOG_SOURCE_3_1A = "systemVerilogSource-3.1a"
    SYSTEM_VERILOG_SOURCE_2009 = "systemVerilogSource-2009"
    SYSTEM_VERILOG_SOURCE_2012 = "systemVerilogSource-2012"
    SYSTEM_VERILOG_SOURCE_2017 = "systemVerilogSource-2017"
    SYSTEM_CSOURCE = "systemCSource"
    SYSTEM_CSOURCE_2_0 = "systemCSource-2.0"
    SYSTEM_CSOURCE_2_0_1 = "systemCSource-2.0.1"
    SYSTEM_CSOURCE_2_1 = "systemCSource-2.1"
    SYSTEM_CSOURCE_2_2 = "systemCSource-2.2"
    SYSTEM_CSOURCE_2_3 = "systemCSource-2.3"
    SYSTEM_CBINARY_LIBRARY = "systemCBinaryLibrary"
    VERA_SOURCE = "veraSource"
    E_SOURCE = "eSource"
    PERL_SOURCE = "perlSource"
    TCL_SOURCE = "tclSource"
    OVASOURCE = "OVASource"
    SVASOURCE = "SVASource"
    PSL_SOURCE = "pslSource"
    SDC = "SDC"
    VHDL_AMS_SOURCE = "vhdlAmsSource"
    VERILOG_AMS_SOURCE = "verilogAmsSource"
    SYSTEM_CAMS_SOURCE = "systemCAmsSource"
    LIBERTY_SOURCE = "libertySource"
    SPICE_SOURCE = "spiceSource"
    SYSTEM_RDL = "systemRDL"
    SYSTEM_RDL_1_0 = "systemRDL-1.0"
    SYSTEM_RDL_2_0 = "systemRDL-2.0"
    USER = "user"
