from __future__ import annotations

from dataclasses import dataclass, field

from generali.models.com.generali.enterprise_services.core.gbo.common.faults.v1.fault_type_failures import (
    FaultTypeFailures,
)
from generali.models.com.generali.enterprise_services.core.gbo.common.v1.characteristics_type import (
    CharacteristicsType,
)
from generali.models.com.generali.enterprise_services.core.gbo.common.v1.fault_category_code_type import (
    FaultCategoryCodeType,
)
from generali.models.com.generali.enterprise_services.core.gbo.common.v1.fault_severity_code_type import (
    FaultSeverityCodeType,
)
from generali.models.org.oasis_open.docs.wsrf.bf_2.base_fault_type import (
    BaseFaultType,
)

__NAMESPACE__ = (
    "http://generali.com/enterprise-services/core/gbo/common/faults/v1"
)


@dataclass(kw_only=True)
class FaultType(BaseFaultType):
    """
    <description xmlns="">The fault object used to hold values for an error
    occurring within a middleware component, intended to be used as part of
    a SOAP:detail tag within the fault as per the SOAP 1.1
    specification.</description>.

    :ivar name_text: <description xmlns="">A human readable short text
        name for the fault. Required if the Error Code &gt;= 100, may be
        omitted or set to "Success" if the object is being used to
        indicate success.</description>
    :ivar severity_code: <description xmlns="">The degree of severity
        and impact the fault has inccured, provides an indication of the
        level that may be used to trigger different behaviours in the
        consumer. Required if the Error Code &gt;= 100, may be omitted
        or set to "Information" if the object is being used to indicate
        success.</description>
    :ivar category_code: <description xmlns="">A classification of the
        fault indicating whether it has been generated through some
        technical aspect of the interaction or on account of a failure
        of business logic, rules or processing. It provides an
        indication of the type that may be used to trigger different
        behaviours in the consumer. Required if the Error Code &gt;=
        100, may be omitted or set to "Business" if the object is being
        used to indicate success.</description>
    :ivar reason_code: <description xmlns="">An enumeration of the
        reasons why the fault has been generated by the provider.
        Currently this is not used.</description>
    :ivar message_text: <description xmlns="">A human readable
        description of the fault as identified by the Error Code.
        Required if the Error Code &gt;= 100, may be omitted or set to
        "Successfully processed" if the object is being used to indicate
        success.</description>
    :ivar characteristics: <description xmlns="">A component that allows
        characteristics of the fault to be specified in addition to
        those specifically asked for, e.g. Category, Severity,
        etc.</description>
    :ivar failures:
    """

    name_text: None | str = field(
        default=None,
        metadata={
            "name": "NameText",
            "type": "Element",
            "namespace": "http://generali.com/enterprise-services/core/gbo/common/faults/v1",
        },
    )
    severity_code: None | FaultSeverityCodeType = field(
        default=None,
        metadata={
            "name": "SeverityCode",
            "type": "Element",
            "namespace": "http://generali.com/enterprise-services/core/gbo/common/faults/v1",
        },
    )
    category_code: None | FaultCategoryCodeType = field(
        default=None,
        metadata={
            "name": "CategoryCode",
            "type": "Element",
            "namespace": "http://generali.com/enterprise-services/core/gbo/common/faults/v1",
        },
    )
    reason_code: None | str = field(
        default=None,
        metadata={
            "name": "ReasonCode",
            "type": "Element",
            "namespace": "http://generali.com/enterprise-services/core/gbo/common/faults/v1",
        },
    )
    message_text: None | str = field(
        default=None,
        metadata={
            "name": "MessageText",
            "type": "Element",
            "namespace": "http://generali.com/enterprise-services/core/gbo/common/faults/v1",
        },
    )
    characteristics: None | CharacteristicsType = field(
        default=None,
        metadata={
            "name": "Characteristics",
            "type": "Element",
            "namespace": "http://generali.com/enterprise-services/core/gbo/common/faults/v1",
        },
    )
    failures: None | FaultTypeFailures = field(
        default=None,
        metadata={
            "name": "Failures",
            "type": "Element",
            "namespace": "http://generali.com/enterprise-services/core/gbo/common/faults/v1",
        },
    )
